// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package imports_params_def_array_usertype_imported

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type ParamsDefArrayUsertypeImported struct {
	HwsParam []*HelloWorld
	_io *kaitai.Stream
	_root *ParamsDefArrayUsertypeImported
	_parent interface{}
	_f_hw0One bool
	hw0One uint8
	_f_hw1One bool
	hw1One uint8
}
func NewParamsDefArrayUsertypeImported(hwsParam []*HelloWorld) *ParamsDefArrayUsertypeImported {
	return &ParamsDefArrayUsertypeImported{
		HwsParam: hwsParam,
	}
}

func (this *ParamsDefArrayUsertypeImported) Read(io *kaitai.Stream, parent interface{}, root *ParamsDefArrayUsertypeImported) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	return err
}
func (this *ParamsDefArrayUsertypeImported) Hw0One() (v uint8, err error) {
	if (this._f_hw0One) {
		return this.hw0One, nil
	}
	this.hw0One = uint8(this.HwsParam[0].One)
	this._f_hw0One = true
	return this.hw0One, nil
}
func (this *ParamsDefArrayUsertypeImported) Hw1One() (v uint8, err error) {
	if (this._f_hw1One) {
		return this.hw1One, nil
	}
	this.hw1One = uint8(this.HwsParam[1].One)
	this._f_hw1One = true
	return this.hw1One, nil
}
