#!/usr/bin/env bash
# Script to prepare test data by downloading formats from Kaitai Struct Gallery

set -e

# Base directory for test data
BASE_DIR="testdata/formats"
mkdir -p "${BASE_DIR}"

# List of formats to download
declare -A FORMATS=(
  [bcd_user_type_be]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/bcd_user_type_be/bcd_user_type_be.ksy"
  [bcd_user_type_le]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/bcd_user_type_le/bcd_user_type_le.ksy"
  # [bits_byte_aligned]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/bits_byte_aligned/bits_byte_aligned.ksy"
  # [bits_enum]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/bits_enum/bits_enum.ksy"
  # [bits_simple]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/bits_simple/bits_simple.ksy"
  # [buffered_struct]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/buffered_struct/buffered_struct.ksy"
  # [bytes_pad_term]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/bytes_pad_term/bytes_pad_term.ksy"
  # [cast_nested]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/cast_nested/cast_nested.ksy"
  # [cast_to_imported]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/cast_to_imported/cast_to_imported.ksy"
  # [cast_to_top]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/cast_to_top/cast_to_top.ksy"
  # [debug_0]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/debug_0/debug_0.ksy"
  # [debug_enum_name]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/debug_enum_name/debug_enum_name.ksy"
  # [default_big_endian]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/default_big_endian/default_big_endian.ksy"
  # [default_endian_expr_exception]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/default_endian_expr_exception/default_endian_expr_exception.ksy"
  # [default_endian_expr_inherited]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/default_endian_expr_inherited/default_endian_expr_inherited.ksy"
  # [default_endian_expr_is_be]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/default_endian_expr_is_be/default_endian_expr_is_be.ksy"
  # [default_endian_expr_is_le]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/default_endian_expr_is_le/default_endian_expr_is_le.ksy"
  # [default_endian_mod]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/default_endian_mod/default_endian_mod.ksy"
  # [docstrings]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/docstrings/docstrings.ksy"
  # [docstrings_docref]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/docstrings_docref/docstrings_docref.ksy"
  # [enum_0]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/enum_0/enum_0.ksy"
  # [enum_1]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/enum_1/enum_1.ksy"
  # [enum_deep]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/enum_deep/enum_deep.ksy"
  # [enum_deep_literals]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/enum_deep_literals/enum_deep_literals.ksy"
  # [enum_fancy]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/enum_fancy/enum_fancy.ksy"
  # [enum_for_unknown_id]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/enum_for_unknown_id/enum_for_unknown_id.ksy"
  # [enum_if]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/enum_if/enum_if.ksy"
  # [enum_negative]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/enum_negative/enum_negative.ksy"
  # [enum_of_value_inst]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/enum_of_value_inst/enum_of_value_inst.ksy"
  # [enum_to_i]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/enum_to_i/enum_to_i.ksy"
  # [eof_exception_bytes]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/eof_exception_bytes/eof_exception_bytes.ksy"
  # [eof_exception_u4]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/eof_exception_u4/eof_exception_u4.ksy"
  # [expr_0]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/expr_0/expr_0.ksy"
  # [expr_1]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/expr_1/expr_1.ksy"
  # [expr_2]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/expr_2/expr_2.ksy"
  # [expr_3]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/expr_3/expr_3.ksy"
  # [expr_array]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/expr_array/expr_array.ksy"
  # [expr_bytes_cmp]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/expr_bytes_cmp/expr_bytes_cmp.ksy"
  # [expr_enum]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/expr_enum/expr_enum.ksy"
  # [expr_io_eof]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/expr_io_eof/expr_io_eof.ksy"
  # [expr_io_pos]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/expr_io_pos/expr_io_pos.ksy"
  # [expr_mod]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/expr_mod/expr_mod.ksy"
  # [fixed_contents]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/fixed_contents/fixed_contents.ksy"
  # [fixed_struct]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/fixed_struct/fixed_struct.ksy"
  # [float_to_i]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/float_to_i/float_to_i.ksy"
  # [floating_points]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/floating_points/floating_points.ksy"
  # [for_rel_imports]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/for_rel_imports/for_rel_imports.ksy"
  # [hello_world]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/hello_world/hello_world.ksy"
  # [if_instances]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/if_instances/if_instances.ksy"
  # [if_struct]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/if_struct/if_struct.ksy"
  # [if_values]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/if_values/if_values.ksy"
  # [imports0]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/imports0/imports0.ksy"
  # [imports_abs]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/imports_abs/imports_abs.ksy"
  # [imports_abs_abs]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/imports_abs_abs/imports_abs_abs.ksy"
  # [imports_abs_rel]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/imports_abs_rel/imports_abs_rel.ksy"
  # [imports_circular_a]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/imports_circular_a/imports_circular_a.ksy"
  # [imports_circular_b]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/imports_circular_b/imports_circular_b.ksy"
  # [imports_rel_1]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/imports_rel_1/imports_rel_1.ksy"
  # [index_sizes]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/index_sizes/index_sizes.ksy"
  # [index_to_param_eos]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/index_to_param_eos/index_to_param_eos.ksy"
  # [index_to_param_expr]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/index_to_param_expr/index_to_param_expr.ksy"
  # [index_to_param_until]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/index_to_param_until/index_to_param_until.ksy"
  # [instance_io_user]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/instance_io_user/instance_io_user.ksy"
  # [instance_std]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/instance_std/instance_std.ksy"
  # [instance_std_array]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/instance_std_array/instance_std_array.ksy"
  # [instance_user_array]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/instance_user_array/instance_user_array.ksy"
  # [integers]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/integers/integers.ksy"
  # [js_signed_right_shift]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/js_signed_right_shift/js_signed_right_shift.ksy"
  # [ks_path]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/ks_path/ks_path.ksy"
  # [meta_xref]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/meta_xref/meta_xref.ksy"
  # [multiple_use]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/multiple_use/multiple_use.ksy"
  # [nav_parent]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/nav_parent/nav_parent.ksy"
  # [nav_parent2]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/nav_parent2/nav_parent2.ksy"
  # [nav_parent3]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/nav_parent3/nav_parent3.ksy"
  # [nav_parent_false]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/nav_parent_false/nav_parent_false.ksy"
  # [nav_parent_false2]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/nav_parent_false2/nav_parent_false2.ksy"
  # [nav_parent_override]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/nav_parent_override/nav_parent_override.ksy"
  # [nav_parent_switch]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/nav_parent_switch/nav_parent_switch.ksy"
  # [nav_parent_vs_value_inst]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/nav_parent_vs_value_inst/nav_parent_vs_value_inst.ksy"
  # [nav_root]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/nav_root/nav_root.ksy"
  # [nested_same_name]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/nested_same_name/nested_same_name.ksy"
  # [nested_same_name2]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/nested_same_name2/nested_same_name2.ksy"
  # [nested_types]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/nested_types/nested_types.ksy"
  # [nested_types2]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/nested_types2/nested_types2.ksy"
  # [nested_types3]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/nested_types3/nested_types3.ksy"
  # [non_standard]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/non_standard/non_standard.ksy"
  # [opaque_external_type]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/opaque_external_type/opaque_external_type.ksy"
  # [opaque_external_type_02_child]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/opaque_external_type_02_child/opaque_external_type_02_child.ksy"
  # [opaque_external_type_02_parent]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/opaque_external_type_02_parent/opaque_external_type_02_parent.ksy"
  # [opaque_with_param]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/opaque_with_param/opaque_with_param.ksy"
  # [optional_id]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/optional_id/optional_id.ksy"
  # [params_call_short]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/params_call_short/params_call_short.ksy"
  # [params_def]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/params_def/params_def.ksy"
  # [params_pass_struct]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/params_pass_struct/params_pass_struct.ksy"
  # [params_pass_usertype]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/params_pass_usertype/params_pass_usertype.ksy"
  # [position_abs]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/position_abs/position_abs.ksy"
  # [position_in_seq]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/position_in_seq/position_in_seq.ksy"
  # [position_to_end]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/position_to_end/position_to_end.ksy"
  # [process_coerce_bytes]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/process_coerce_bytes/process_coerce_bytes.ksy"
  # [process_coerce_switch]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/process_coerce_switch/process_coerce_switch.ksy"
  # [process_coerce_usertype1]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/process_coerce_usertype1/process_coerce_usertype1.ksy"
  # [process_coerce_usertype2]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/process_coerce_usertype2/process_coerce_usertype2.ksy"
  # [process_custom]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/process_custom/process_custom.ksy"
  # [process_rotate]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/process_rotate/process_rotate.ksy"
  # [process_to_user]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/process_to_user/process_to_user.ksy"
  # [process_xor4_const]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/process_xor4_const/process_xor4_const.ksy"
  # [process_xor4_value]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/process_xor4_value/process_xor4_value.ksy"
  # [process_xor_const]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/process_xor_const/process_xor_const.ksy"
  # [process_xor_value]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/process_xor_value/process_xor_value.ksy"
  # [recursive_one]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/recursive_one/recursive_one.ksy"
  # [repeat_eos_struct]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/repeat_eos_struct/repeat_eos_struct.ksy"
  # [repeat_eos_u4]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/repeat_eos_u4/repeat_eos_u4.ksy"
  # [repeat_n_struct]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/repeat_n_struct/repeat_n_struct.ksy"
  # [repeat_n_strz]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/repeat_n_strz/repeat_n_strz.ksy"
  # [repeat_n_strz_double]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/repeat_n_strz_double/repeat_n_strz_double.ksy"
  # [repeat_until_complex]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/repeat_until_complex/repeat_until_complex.ksy"
  # [repeat_until_s4]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/repeat_until_s4/repeat_until_s4.ksy"
  # [repeat_until_sized]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/repeat_until_sized/repeat_until_sized.ksy"
  # [str_encodings]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/str_encodings/str_encodings.ksy"
  # [str_encodings_default]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/str_encodings_default/str_encodings_default.ksy"
  # [str_eos]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/str_eos/str_eos.ksy"
  # [str_literals]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/str_literals/str_literals.ksy"
  # [str_literals2]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/str_literals2/str_literals2.ksy"
  # [str_pad_term]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/str_pad_term/str_pad_term.ksy"
  # [str_pad_term_empty]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/str_pad_term_empty/str_pad_term_empty.ksy"
  # [switch_bytearray]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/switch_bytearray/switch_bytearray.ksy"
  # [switch_cast]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/switch_cast/switch_cast.ksy"
  # [switch_integers]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/switch_integers/switch_integers.ksy"
  # [switch_integers2]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/switch_integers2/switch_integers2.ksy"
  # [switch_manual_enum]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/switch_manual_enum/switch_manual_enum.ksy"
  # [switch_manual_int]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/switch_manual_int/switch_manual_int.ksy"
  # [switch_manual_int_else]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/switch_manual_int_else/switch_manual_int_else.ksy"
  # [switch_manual_int_size]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/switch_manual_int_size/switch_manual_int_size.ksy"
  # [switch_manual_int_size_else]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/switch_manual_int_size_else/switch_manual_int_size_else.ksy"
  # [switch_manual_int_size_eos]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/switch_manual_int_size_eos/switch_manual_int_size_eos.ksy"
  # [switch_manual_str]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/switch_manual_str/switch_manual_str.ksy"
  # [switch_manual_str_else]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/switch_manual_str_else/switch_manual_str_else.ksy"
  # [switch_multi_bool_ops]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/switch_multi_bool_ops/switch_multi_bool_ops.ksy"
  # [switch_repeat_expr]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/switch_repeat_expr/switch_repeat_expr.ksy"
  # [term_bytes]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/term_bytes/term_bytes.ksy"
  # [term_strz]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/term_strz/term_strz.ksy"
  # [ts_packet_header]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/ts_packet_header/ts_packet_header.ksy"
  # [type_int_unary_op]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/type_int_unary_op/type_int_unary_op.ksy"
  # [type_ternary]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/type_ternary/type_ternary.ksy"
  # [type_ternary_opaque]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/type_ternary_opaque/type_ternary_opaque.ksy"
  # [user_type]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/user_type/user_type.ksy"
  # [yaml_ints]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/yaml_ints/yaml_ints.ksy"
  # [zlib_with_header_78]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/tests/kaitai/zlib_with_header_78/zlib_with_header_78.ksy"

)

# List of formats to download
declare -A SAMPLE=(
  [bcd_user_type_be.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/bcd_user_type_be.bin"
  [bcd_user_type_le.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/bcd_user_type_le.bin"
  # [buffered_struct.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/buffered_struct.bin"
  # [endian_expr.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/endian_expr.bin"
  # [enum_0.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/enum_0.bin"
  # [enum_negative.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/enum_negative.bin"
  # [expr_array.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/expr_array.bin"
  # [expr_io_pos.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/expr_io_pos.bin"
  # [fixed_struct.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/fixed_struct.bin"
  # [floating_points.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/floating_points.bin"
  # [if_struct.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/if_struct.bin"
  # [index_sizes.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/index_sizes.bin"
  # [instance_io.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/instance_io.bin"
  # [instance_std_array.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/instance_std_array.bin"
  # [nav.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/nav.bin"
  # [nav_parent2.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/nav_parent2.bin"
  # [nav_parent_codes.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/nav_parent_codes.bin"
  # [nav_parent_switch.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/nav_parent_switch.bin"
  # [nested_same_name2.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/nested_same_name2.bin"
  # [position_abs.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/position_abs.bin"
  # [position_in_seq.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/position_in_seq.bin"
  # [position_to_end.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/position_to_end.bin"
  # [process_coerce_bytes.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/process_coerce_bytes.bin"
  # [process_coerce_switch.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/process_coerce_switch.bin"
  # [process_rotate.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/process_rotate.bin"
  # [process_xor_1.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/process_xor_1.bin"
  # [process_xor_4.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/process_xor_4.bin"
  # [repeat_eos_struct.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/repeat_eos_struct.bin"
  # [repeat_n_struct.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/repeat_n_struct.bin"
  # [repeat_n_strz.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/repeat_n_strz.bin"
  # [repeat_until_complex.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/repeat_until_complex.bin"
  # [repeat_until_process.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/repeat_until_process.bin"
  # [repeat_until_s4.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/repeat_until_s4.bin"
  # [str_encodings.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/str_encodings.bin"
  # [str_pad_term.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/str_pad_term.bin"
  # [str_pad_term_empty.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/str_pad_term_empty.bin"
  # [switch_integers.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/switch_integers.bin"
  # [switch_opcodes.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/switch_opcodes.bin"
  # [switch_opcodes2.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/switch_opcodes2.bin"
  # [switch_tlv.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/switch_tlv.bin"
  # [term_strz.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/term_strz.bin"
  # [ts_packet.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/ts_packet.bin"
  # [zlib_with_header_78.bin]="https://github.com/khalidDaoud/kaitaigo/raw/refs/heads/master/testdata/kaitai/zlib_with_header_78.bin"
)

# Download formats and samples
for format in "${!FORMATS[@]}"; do
  format_dir="${BASE_DIR}/${format}"
  samples_dir="${format_dir}/samples"
  mkdir -p "${format_dir}" "${samples_dir}"
  
  echo "Downloading schema for ${format}..."
  curl -L -o "${format_dir}/${format}.ksy" "${FORMATS[$format]}"
  
done

# Download each sample
for sample in "${!SAMPLE[@]}"; do
  sample_file="${samples_dir}/$(basename ${sample})"
  echo "Downloading sample ${sample}..."
  curl -L -o "${sample_file}.bin" "${SAMPLE[$sample]}"
      
  # For each binary sample, create an initial JSON file if it doesn't exist
  json_file="${sample_file%.*}.json"
  if [ ! -f "${json_file}" ]; then
    echo "Creating initial JSON for ${sample_file}..."
    echo '{"sample": "'$(basename ${sample})'", "format": "'${format}'"}' > "${json_file}"
  fi
  done
  
done

# Create a Benthos test configuration
mkdir -p test
cat > test/benthos_test_config.yaml << EOF
input:
  file:
    paths: ["${BASE_DIR}/png/samples/*.png"]
    codec: raw

pipeline:
  processors:
    - kaitai:
        schema_path: "${BASE_DIR}/png/png.ksy"
        is_parser: true

output:
  file:
    path: "test/output.json"
    codec: json
EOF

echo "Test data preparation complete!"
