name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Install dependencies
        run: |
          go mod download
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Setup test data
        run: ./scripts/prepare_test_data.sh

      - name: Lint
        run: golangci-lint run ./...

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
          fail_ci_if_error: true

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Build Benthos plugin
        run: go build -o benthos-kaitai ./cmd/benthos-kaitai

      - name: Run integration tests
        run: ./scripts/integration_test.sh

  integration:
    name: Benthos Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Install Benthos
        run: |
          curl -Lsf https://sh.benthos.dev | bash
          benthos --version

      - name: Build plugin
        run: go build -o benthos-kaitai ./cmd/benthos-kaitai
      
      - name: Setup test data
        run: ./scripts/prepare_test_data.sh

      - name: Run Benthos with plugin
        run: |
          benthos --plugin-dir=. -c ./test/benthos_test_config.yaml
