// Code generated by kaitai-test-gen-simple.go; DO NOT EDIT.
package formats_test

import (
	"bytes"
	"context"
	"log/slog"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/twinfer/kbin-plugin/pkg/kaitaistruct"
	bits_simple_kaitai "github.com/twinfer/kbin-plugin/testdata/formats_kaitai_go_gen/bits_simple"
)

func TestParse_BitsSimple(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "bits_simple.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)
	logger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug}))
	interpreter, err := kaitaistruct.NewKaitaiInterpreter(schema, logger)
	require.NoError(t, err)

	// Read binary file
	binPath := filepath.Join("../../../test/src", "fixed_struct.bin")
	binData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse with custom parser
	stream := kaitai.NewStream(bytes.NewReader(binData))
	parsed, err := interpreter.Parse(context.Background(), stream)
	require.NoError(t, err)

	// Convert to map for assertions
	customMap := kaitaistruct.ParsedDataToMap(parsed).(map[string]any)

	// Assertions from KSC test

	// Assert Byte1
	if byte1_val, ok := customMap["Byte1"]; ok {
		assert.EqualValues(t, 80, byte1_val)
	} else {
		t.Fatalf("Field 'Byte1' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Byte2
	if byte2_val, ok := customMap["Byte2"]; ok {
		assert.EqualValues(t, 65, byte2_val)
	} else {
		t.Fatalf("Field 'Byte2' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert BitsA
	if bitsa_val, ok := customMap["BitsA"]; ok {
		assert.EqualValues(t, false, bitsa_val)
	} else {
		t.Fatalf("Field 'BitsA' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert BitsB
	if bitsb_val, ok := customMap["BitsB"]; ok {
		assert.EqualValues(t, 4, bitsb_val)
	} else {
		t.Fatalf("Field 'BitsB' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert BitsC
	if bitsc_val, ok := customMap["BitsC"]; ok {
		assert.EqualValues(t, 3, bitsc_val)
	} else {
		t.Fatalf("Field 'BitsC' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert LargeBits1
	if largebits1_val, ok := customMap["LargeBits1"]; ok {
		assert.EqualValues(t, 300, largebits1_val)
	} else {
		t.Fatalf("Field 'LargeBits1' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Spacer
	if spacer_val, ok := customMap["Spacer"]; ok {
		assert.EqualValues(t, 5, spacer_val)
	} else {
		t.Fatalf("Field 'Spacer' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert LargeBits2
	if largebits2_val, ok := customMap["LargeBits2"]; ok {
		assert.EqualValues(t, 1329, largebits2_val)
	} else {
		t.Fatalf("Field 'LargeBits2' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert NormalS2
	if normals2_val, ok := customMap["NormalS2"]; ok {
		assert.EqualValues(t, -1, normals2_val)
	} else {
		t.Fatalf("Field 'NormalS2' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Byte8910
	if byte8910_val, ok := customMap["Byte8910"]; ok {
		assert.EqualValues(t, 5259587, byte8910_val)
	} else {
		t.Fatalf("Field 'Byte8910' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Byte11To14
	if byte11to14_val, ok := customMap["Byte11To14"]; ok {
		assert.EqualValues(t, 1261262125, byte11to14_val)
	} else {
		t.Fatalf("Field 'Byte11To14' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Byte15To19
	if byte15to19_val, ok := customMap["Byte15To19"]; ok {
		assert.EqualValues(t, int64(293220057087), byte15to19_val)
	} else {
		t.Fatalf("Field 'Byte15To19' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Byte20To27
	if byte20to27_val, ok := customMap["Byte20To27"]; ok {
		assert.EqualValues(t, uint64(18446744073709551615), byte20to27_val)
	} else {
		t.Fatalf("Field 'Byte20To27' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert TestIfB1
	if testifb1_val, ok := customMap["TestIfB1"]; ok {
		assert.EqualValues(t, 123, testifb1_val)
	} else {
		t.Fatalf("Field 'TestIfB1' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

}

func TestSerialize_BitsSimple(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "bits_simple.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)

	serializer, err := kaitaistruct.NewKaitaiSerializer(schema, nil)
	require.NoError(t, err)

	// Read original binary
	binPath := filepath.Join("../../../test/src", "fixed_struct.bin")
	originalData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse original
	stream := kaitai.NewStream(bytes.NewReader(originalData))
	original := bits_simple_kaitai.NewBitsSimple()
	err = original.Read(stream, original, original)
	require.NoError(t, err)

	// Serialize and verify round-trip
	inputMap := structToMapBitsSimple(t, original)

	serialized, err := serializer.Serialize(context.Background(), inputMap)
	require.NoError(t, err)

	// Parse serialized data
	stream2 := kaitai.NewStream(bytes.NewReader(serialized))
	reparsed := bits_simple_kaitai.NewBitsSimple()
	err = reparsed.Read(stream2, reparsed, reparsed)
	require.NoError(t, err)

	// Compare structures with Phase 2/3 enhanced comparison
	cmpOpts := []cmp.Option{
		cmpopts.IgnoreUnexported(
			kaitai.Stream{},
		),
		cmpopts.IgnoreFields(bits_simple_kaitai.BitsSimple{}, "_io", "_parent", "_root"),
		cmpopts.EquateEmpty(),
	}
	if diff := cmp.Diff(original, reparsed, cmpOpts...); diff != "" {
		t.Errorf("Serialization mismatch (-original +reparsed):\n%s", diff)
	}
}

// structToMapBitsSimple converts KSC struct to map for serializer
func structToMapBitsSimple(t *testing.T, data any) map[string]any {
	// Use reflection to handle KSC structs with method-based values
	return structToMapReflectiveBitsSimple(t, data)
}

// structToMapReflectiveBitsSimple uses reflection to convert KSC structs including method calls
func structToMapReflectiveBitsSimple(t *testing.T, data any) map[string]any {
	result := make(map[string]any)

	val := reflect.ValueOf(data)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	typ := val.Type()

	// Process fields
	for i := 0; i < val.NumField(); i++ {
		field := typ.Field(i)
		fieldVal := val.Field(i)

		// Skip internal KSC fields
		if strings.HasPrefix(field.Name, "_") {
			continue
		}

		fieldName := strings.ToLower(field.Name)

		if !fieldVal.IsValid() || fieldVal.IsZero() {
			continue
		}

		// Handle different field types
		switch fieldVal.Kind() {
		case reflect.Ptr:
			if !fieldVal.IsNil() {
				// For custom types, check for AsInt/AsStr methods
				subResult := make(map[string]any)

				// Try to call AsInt method
				if method := fieldVal.MethodByName("AsInt"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asint"] = results[0].Interface()
					}
				}

				// Try to call AsStr method
				if method := fieldVal.MethodByName("AsStr"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asstr"] = results[0].Interface()
					}
				}

				// Also include raw fields
				subMap := structToMapReflectiveBitsSimple(t, fieldVal.Interface())
				for k, v := range subMap {
					if _, exists := subResult[k]; !exists {
						subResult[k] = v
					}
				}

				result[fieldName] = subResult
			}
		case reflect.Slice:
			if fieldVal.Len() > 0 {
				slice := make([]any, fieldVal.Len())
				for j := 0; j < fieldVal.Len(); j++ {
					slice[j] = fieldVal.Index(j).Interface()
				}
				result[fieldName] = slice
			}
		default:
			result[fieldName] = fieldVal.Interface()
		}
	}

	return result
}
