// Code generated by kaitai-test-gen-simple.go; DO NOT EDIT.
package formats_test

import (
	"bytes"
	"context"
	"io"
	"log/slog"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/twinfer/kbin-plugin/pkg/kaitaistruct"
	bits_byte_aligned_kaitai "github.com/twinfer/kbin-plugin/testdata/formats_kaitai_go_gen/bits_byte_aligned"
)

func TestParse_BitsByteAligned(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "bits_byte_aligned.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)
	logger := slog.New(slog.NewTextHandler(io.Discard, nil))
	interpreter, err := kaitaistruct.NewKaitaiInterpreter(schema, logger)
	require.NoError(t, err)

	// Read binary file
	binPath := filepath.Join("../../../test/src", "fixed_struct.bin")
	binData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse with custom parser
	stream := kaitai.NewStream(bytes.NewReader(binData))
	parsed, err := interpreter.Parse(context.Background(), stream)
	require.NoError(t, err)

	// Convert to map for assertions
	customMap := kaitaistruct.ParsedDataToMap(parsed).(map[string]any)

	// Assertions from KSC test

	// Assert One
	if one_val, ok := customMap["one"]; ok {
		assert.EqualValues(t, 20, one_val)
	} else {
		t.Fatalf("Field 'one' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Byte1
	if byte_1_val, ok := customMap["byte_1"]; ok {
		assert.EqualValues(t, 65, byte_1_val)
	} else {
		t.Fatalf("Field 'byte_1' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Two
	if two_val, ok := customMap["two"]; ok {
		assert.EqualValues(t, 2, two_val)
	} else {
		t.Fatalf("Field 'two' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Three
	if three_val, ok := customMap["three"]; ok {
		assert.EqualValues(t, false, three_val)
	} else {
		t.Fatalf("Field 'three' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Byte2
	if byte_2_val, ok := customMap["byte_2"]; ok {
		assert.EqualValues(t, 75, byte_2_val)
	} else {
		t.Fatalf("Field 'byte_2' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Four
	if four_val, ok := customMap["four"]; ok {
		assert.EqualValues(t, 2892, four_val)
	} else {
		t.Fatalf("Field 'four' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Byte3
	if byte_3_val, ok := customMap["byte_3"]; ok {
		assert.EqualValues(t, []uint8{255}, byte_3_val)
	} else {
		t.Fatalf("Field 'byte_3' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert FullByte
	if full_byte_val, ok := customMap["full_byte"]; ok {
		assert.EqualValues(t, 255, full_byte_val)
	} else {
		t.Fatalf("Field 'full_byte' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Byte4
	if byte_4_val, ok := customMap["byte_4"]; ok {
		assert.EqualValues(t, 80, byte_4_val)
	} else {
		t.Fatalf("Field 'byte_4' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

}

func TestSerialize_BitsByteAligned(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "bits_byte_aligned.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)

	serializer, err := kaitaistruct.NewKaitaiSerializer(schema, nil)
	require.NoError(t, err)

	// Read original binary
	binPath := filepath.Join("../../../test/src", "fixed_struct.bin")
	originalData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse original
	stream := kaitai.NewStream(bytes.NewReader(originalData))
	original := bits_byte_aligned_kaitai.NewBitsByteAligned()
	err = original.Read(stream, original, original)
	require.NoError(t, err)

	// Serialize and verify round-trip
	inputMap := structToMapBitsByteAligned(t, original)

	serialized, err := serializer.Serialize(context.Background(), inputMap)
	require.NoError(t, err)

	// Parse serialized data
	stream2 := kaitai.NewStream(bytes.NewReader(serialized))
	reparsed := bits_byte_aligned_kaitai.NewBitsByteAligned()
	err = reparsed.Read(stream2, reparsed, reparsed)
	require.NoError(t, err)

	// Compare structures with Phase 2/3 enhanced comparison
	cmpOpts := []cmp.Option{
		cmpopts.IgnoreUnexported(
			kaitai.Stream{},
		),
		cmpopts.IgnoreFields(bits_byte_aligned_kaitai.BitsByteAligned{}, "_io", "_parent", "_root"),
		cmpopts.EquateEmpty(),
	}
	if diff := cmp.Diff(original, reparsed, cmpOpts...); diff != "" {
		t.Errorf("Serialization mismatch (-original +reparsed):\n%s", diff)
	}
}

// structToMapBitsByteAligned converts KSC struct to map for serializer
func structToMapBitsByteAligned(t *testing.T, data any) map[string]any {
	// Use reflection to handle KSC structs with method-based values
	return structToMapReflectiveBitsByteAligned(t, data)
}

// structToMapReflectiveBitsByteAligned uses reflection to convert KSC structs including method calls
func structToMapReflectiveBitsByteAligned(t *testing.T, data any) map[string]any {
	result := make(map[string]any)

	val := reflect.ValueOf(data)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	typ := val.Type()

	// Process fields
	for i := 0; i < val.NumField(); i++ {
		field := typ.Field(i)
		fieldVal := val.Field(i)

		// Skip internal KSC fields
		if strings.HasPrefix(field.Name, "_") {
			continue
		}

		fieldName := strings.ToLower(field.Name)

		if !fieldVal.IsValid() || fieldVal.IsZero() {
			continue
		}

		// Handle different field types
		switch fieldVal.Kind() {
		case reflect.Ptr:
			if !fieldVal.IsNil() {
				// For custom types, check for AsInt/AsStr methods
				subResult := make(map[string]any)

				// Try to call AsInt method
				if method := fieldVal.MethodByName("AsInt"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asint"] = results[0].Interface()
					}
				}

				// Try to call AsStr method
				if method := fieldVal.MethodByName("AsStr"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asstr"] = results[0].Interface()
					}
				}

				// Also include raw fields
				subMap := structToMapReflectiveBitsByteAligned(t, fieldVal.Interface())
				for k, v := range subMap {
					if _, exists := subResult[k]; !exists {
						subResult[k] = v
					}
				}

				result[fieldName] = subResult
			}
		case reflect.Slice:
			if fieldVal.Len() > 0 {
				slice := make([]any, fieldVal.Len())
				for j := 0; j < fieldVal.Len(); j++ {
					slice[j] = fieldVal.Index(j).Interface()
				}
				result[fieldName] = slice
			}
		default:
			result[fieldName] = fieldVal.Interface()
		}
	}

	return result
}
