// Code generated by kaitai-test-gen-simple.go; DO NOT EDIT.
package formats_test

import (
	"bytes"
	"context"
	"io"
	"log/slog"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/twinfer/kbin-plugin/pkg/kaitaistruct"
	bits_simple_kaitai "github.com/twinfer/kbin-plugin/testdata/formats_kaitai_go_gen/bits_simple"
)

func TestParse_BitsSimple(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "bits_simple.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)
	logger := slog.New(slog.NewTextHandler(io.Discard, nil))
	interpreter, err := kaitaistruct.NewKaitaiInterpreter(schema, logger)
	require.NoError(t, err)

	// Read binary file
	binPath := filepath.Join("../../../test/src", "fixed_struct.bin")
	binData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse with custom parser
	stream := kaitai.NewStream(bytes.NewReader(binData))
	parsed, err := interpreter.Parse(context.Background(), stream)
	require.NoError(t, err)

	// Convert to map for assertions
	customMap := kaitaistruct.ParsedDataToMap(parsed).(map[string]any)

	// Assertions from KSC test

	// Assert Byte1
	if byte_1_val, ok := customMap["byte_1"]; ok {
		assert.EqualValues(t, 80, byte_1_val)
	} else {
		t.Fatalf("Field 'byte_1' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Byte2
	if byte_2_val, ok := customMap["byte_2"]; ok {
		assert.EqualValues(t, 65, byte_2_val)
	} else {
		t.Fatalf("Field 'byte_2' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert BitsA
	if bits_a_val, ok := customMap["bits_a"]; ok {
		assert.EqualValues(t, false, bits_a_val)
	} else {
		t.Fatalf("Field 'bits_a' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert BitsB
	if bits_b_val, ok := customMap["bits_b"]; ok {
		assert.EqualValues(t, 4, bits_b_val)
	} else {
		t.Fatalf("Field 'bits_b' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert BitsC
	if bits_c_val, ok := customMap["bits_c"]; ok {
		assert.EqualValues(t, 3, bits_c_val)
	} else {
		t.Fatalf("Field 'bits_c' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert LargeBits1
	if large_bits_1_val, ok := customMap["large_bits_1"]; ok {
		assert.EqualValues(t, 300, large_bits_1_val)
	} else {
		t.Fatalf("Field 'large_bits_1' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Spacer
	if spacer_val, ok := customMap["spacer"]; ok {
		assert.EqualValues(t, 5, spacer_val)
	} else {
		t.Fatalf("Field 'spacer' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert LargeBits2
	if large_bits_2_val, ok := customMap["large_bits_2"]; ok {
		assert.EqualValues(t, 1329, large_bits_2_val)
	} else {
		t.Fatalf("Field 'large_bits_2' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert NormalS2
	if normal_s2_val, ok := customMap["normal_s2"]; ok {
		assert.EqualValues(t, -1, normal_s2_val)
	} else {
		t.Fatalf("Field 'normal_s2' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Byte8910
	if byte_8_9_10_val, ok := customMap["byte_8_9_10"]; ok {
		assert.EqualValues(t, 5259587, byte_8_9_10_val)
	} else {
		t.Fatalf("Field 'byte_8_9_10' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Byte11To14
	if byte_11_to_14_val, ok := customMap["byte_11_to_14"]; ok {
		assert.EqualValues(t, 1261262125, byte_11_to_14_val)
	} else {
		t.Fatalf("Field 'byte_11_to_14' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Byte15To19
	if byte_15_to_19_val, ok := customMap["byte_15_to_19"]; ok {
		assert.EqualValues(t, int64(293220057087), byte_15_to_19_val)
	} else {
		t.Fatalf("Field 'byte_15_to_19' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Byte20To27
	if byte_20_to_27_val, ok := customMap["byte_20_to_27"]; ok {
		assert.EqualValues(t, uint64(18446744073709551615), byte_20_to_27_val)
	} else {
		t.Fatalf("Field 'byte_20_to_27' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert TestIfB1
	if test_if_b1_val, ok := customMap["test_if_b1"]; ok {
		assert.EqualValues(t, 123, test_if_b1_val)
	} else {
		t.Fatalf("Field 'test_if_b1' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

}

func TestSerialize_BitsSimple(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "bits_simple.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)

	serializer, err := kaitaistruct.NewKaitaiSerializer(schema, nil)
	require.NoError(t, err)

	// Read original binary
	binPath := filepath.Join("../../../test/src", "fixed_struct.bin")
	originalData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse original
	stream := kaitai.NewStream(bytes.NewReader(originalData))
	original := bits_simple_kaitai.NewBitsSimple()
	err = original.Read(stream, original, original)
	require.NoError(t, err)

	// Serialize and verify round-trip
	inputMap := structToMapBitsSimple(t, original)

	serialized, err := serializer.Serialize(context.Background(), inputMap)
	require.NoError(t, err)

	// Parse serialized data
	stream2 := kaitai.NewStream(bytes.NewReader(serialized))
	reparsed := bits_simple_kaitai.NewBitsSimple()
	err = reparsed.Read(stream2, reparsed, reparsed)
	require.NoError(t, err)

	// Compare structures with Phase 2/3 enhanced comparison
	cmpOpts := []cmp.Option{
		cmpopts.IgnoreUnexported(
			kaitai.Stream{},
		),
		cmpopts.IgnoreFields(bits_simple_kaitai.BitsSimple{}, "_io", "_parent", "_root"),
		cmpopts.EquateEmpty(),
	}
	if diff := cmp.Diff(original, reparsed, cmpOpts...); diff != "" {
		t.Errorf("Serialization mismatch (-original +reparsed):\n%s", diff)
	}
}

// structToMapBitsSimple converts KSC struct to map for serializer
func structToMapBitsSimple(t *testing.T, data any) map[string]any {
	// Use reflection to handle KSC structs with method-based values
	return structToMapReflectiveBitsSimple(t, data)
}

// structToMapReflectiveBitsSimple uses reflection to convert KSC structs including method calls
func structToMapReflectiveBitsSimple(t *testing.T, data any) map[string]any {
	result := make(map[string]any)

	val := reflect.ValueOf(data)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	typ := val.Type()

	// Process fields
	for i := 0; i < val.NumField(); i++ {
		field := typ.Field(i)
		fieldVal := val.Field(i)

		// Skip internal KSC fields
		if strings.HasPrefix(field.Name, "_") {
			continue
		}

		fieldName := strings.ToLower(field.Name)

		if !fieldVal.IsValid() || fieldVal.IsZero() {
			continue
		}

		// Handle different field types
		switch fieldVal.Kind() {
		case reflect.Ptr:
			if !fieldVal.IsNil() {
				// For custom types, check for AsInt/AsStr methods
				subResult := make(map[string]any)

				// Try to call AsInt method
				if method := fieldVal.MethodByName("AsInt"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asint"] = results[0].Interface()
					}
				}

				// Try to call AsStr method
				if method := fieldVal.MethodByName("AsStr"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asstr"] = results[0].Interface()
					}
				}

				// Also include raw fields
				subMap := structToMapReflectiveBitsSimple(t, fieldVal.Interface())
				for k, v := range subMap {
					if _, exists := subResult[k]; !exists {
						subResult[k] = v
					}
				}

				result[fieldName] = subResult
			}
		case reflect.Slice:
			if fieldVal.Len() > 0 {
				slice := make([]any, fieldVal.Len())
				for j := 0; j < fieldVal.Len(); j++ {
					slice[j] = fieldVal.Index(j).Interface()
				}
				result[fieldName] = slice
			}
		default:
			result[fieldName] = fieldVal.Interface()
		}
	}

	return result
}
