// Code generated by kaitai-test-gen-simple.go; DO NOT EDIT.
package formats_test

import (
	"bytes"
	"context"
	"log/slog"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/twinfer/kbin-plugin/pkg/kaitaistruct"
	buffered_struct_kaitai "github.com/twinfer/kbin-plugin/testdata/formats_kaitai_go_gen/buffered_struct"
)

func TestParse_BufferedStruct(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "buffered_struct.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)
	logger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug}))
	interpreter, err := kaitaistruct.NewKaitaiInterpreter(schema, logger)
	require.NoError(t, err)

	// Read binary file
	binPath := filepath.Join("../../../test/src", "buffered_struct.bin")
	binData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse with custom parser
	stream := kaitai.NewStream(bytes.NewReader(binData))
	parsed, err := interpreter.Parse(context.Background(), stream)
	require.NoError(t, err)

	// Convert to map for assertions
	customMap := kaitaistruct.ParsedDataToMap(parsed).(map[string]any)

	// Assertions from KSC test

	// Assert Len1
	if len1_val, ok := customMap["Len1"]; ok {
		assert.EqualValues(t, 16, len1_val)
	} else {
		t.Fatalf("Field 'Len1' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Block1.Number1
	if block1_number1_lvl0_map, ok := customMap["Block1"].(map[string]any); ok {
		if block1_number1_val, ok := block1_number1_lvl0_map["Number1"]; ok {
			assert.EqualValues(t, 66, block1_number1_val)
		} else {
			t.Fatalf("Field 'Number1' not found in block1_number1_lvl0_map (keys: %v)", maps.Keys(block1_number1_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'Block1' not found or not a map while asserting Block1.Number1")
	}

	// Assert Block1.Number2
	if block1_number2_lvl0_map, ok := customMap["Block1"].(map[string]any); ok {
		if block1_number2_val, ok := block1_number2_lvl0_map["Number2"]; ok {
			assert.EqualValues(t, 67, block1_number2_val)
		} else {
			t.Fatalf("Field 'Number2' not found in block1_number2_lvl0_map (keys: %v)", maps.Keys(block1_number2_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'Block1' not found or not a map while asserting Block1.Number2")
	}

	// Assert Len2
	if len2_val, ok := customMap["Len2"]; ok {
		assert.EqualValues(t, 8, len2_val)
	} else {
		t.Fatalf("Field 'Len2' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Block2.Number1
	if block2_number1_lvl0_map, ok := customMap["Block2"].(map[string]any); ok {
		if block2_number1_val, ok := block2_number1_lvl0_map["Number1"]; ok {
			assert.EqualValues(t, 68, block2_number1_val)
		} else {
			t.Fatalf("Field 'Number1' not found in block2_number1_lvl0_map (keys: %v)", maps.Keys(block2_number1_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'Block2' not found or not a map while asserting Block2.Number1")
	}

	// Assert Block2.Number2
	if block2_number2_lvl0_map, ok := customMap["Block2"].(map[string]any); ok {
		if block2_number2_val, ok := block2_number2_lvl0_map["Number2"]; ok {
			assert.EqualValues(t, 69, block2_number2_val)
		} else {
			t.Fatalf("Field 'Number2' not found in block2_number2_lvl0_map (keys: %v)", maps.Keys(block2_number2_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'Block2' not found or not a map while asserting Block2.Number2")
	}

	// Assert Finisher
	if finisher_val, ok := customMap["Finisher"]; ok {
		assert.EqualValues(t, 238, finisher_val)
	} else {
		t.Fatalf("Field 'Finisher' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

}

func TestSerialize_BufferedStruct(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "buffered_struct.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)

	serializer, err := kaitaistruct.NewKaitaiSerializer(schema, nil)
	require.NoError(t, err)

	// Read original binary
	binPath := filepath.Join("../../../test/src", "buffered_struct.bin")
	originalData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse original
	stream := kaitai.NewStream(bytes.NewReader(originalData))
	original := buffered_struct_kaitai.NewBufferedStruct()
	err = original.Read(stream, original, original)
	require.NoError(t, err)

	// Serialize and verify round-trip
	inputMap := structToMapBufferedStruct(t, original)

	serialized, err := serializer.Serialize(context.Background(), inputMap)
	require.NoError(t, err)

	// Parse serialized data
	stream2 := kaitai.NewStream(bytes.NewReader(serialized))
	reparsed := buffered_struct_kaitai.NewBufferedStruct()
	err = reparsed.Read(stream2, reparsed, reparsed)
	require.NoError(t, err)

	// Compare structures with Phase 2/3 enhanced comparison
	cmpOpts := []cmp.Option{
		cmpopts.IgnoreUnexported(
			kaitai.Stream{},
		),
		cmpopts.IgnoreFields(buffered_struct_kaitai.BufferedStruct{}, "_io", "_parent", "_root"),
		cmpopts.EquateEmpty(),
	}
	if diff := cmp.Diff(original, reparsed, cmpOpts...); diff != "" {
		t.Errorf("Serialization mismatch (-original +reparsed):\n%s", diff)
	}
}

// structToMapBufferedStruct converts KSC struct to map for serializer
func structToMapBufferedStruct(t *testing.T, data any) map[string]any {
	// Use reflection to handle KSC structs with method-based values
	return structToMapReflectiveBufferedStruct(t, data)
}

// structToMapReflectiveBufferedStruct uses reflection to convert KSC structs including method calls
func structToMapReflectiveBufferedStruct(t *testing.T, data any) map[string]any {
	result := make(map[string]any)

	val := reflect.ValueOf(data)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	typ := val.Type()

	// Process fields
	for i := 0; i < val.NumField(); i++ {
		field := typ.Field(i)
		fieldVal := val.Field(i)

		// Skip internal KSC fields
		if strings.HasPrefix(field.Name, "_") {
			continue
		}

		fieldName := strings.ToLower(field.Name)

		if !fieldVal.IsValid() || fieldVal.IsZero() {
			continue
		}

		// Handle different field types
		switch fieldVal.Kind() {
		case reflect.Ptr:
			if !fieldVal.IsNil() {
				// For custom types, check for AsInt/AsStr methods
				subResult := make(map[string]any)

				// Try to call AsInt method
				if method := fieldVal.MethodByName("AsInt"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asint"] = results[0].Interface()
					}
				}

				// Try to call AsStr method
				if method := fieldVal.MethodByName("AsStr"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asstr"] = results[0].Interface()
					}
				}

				// Also include raw fields
				subMap := structToMapReflectiveBufferedStruct(t, fieldVal.Interface())
				for k, v := range subMap {
					if _, exists := subResult[k]; !exists {
						subResult[k] = v
					}
				}

				result[fieldName] = subResult
			}
		case reflect.Slice:
			if fieldVal.Len() > 0 {
				slice := make([]any, fieldVal.Len())
				for j := 0; j < fieldVal.Len(); j++ {
					slice[j] = fieldVal.Index(j).Interface()
				}
				result[fieldName] = slice
			}
		default:
			result[fieldName] = fieldVal.Interface()
		}
	}

	return result
}
