// Code generated by kaitai-test-gen-simple.go; DO NOT EDIT.
package formats_test

import (
	"bytes"
	"context"
	"log/slog"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/twinfer/kbin-plugin/pkg/kaitaistruct"
	combine_bytes_kaitai "github.com/twinfer/kbin-plugin/testdata/formats_kaitai_go_gen/combine_bytes"
)

func TestParse_CombineBytes(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "combine_bytes.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)
	logger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug}))
	interpreter, err := kaitaistruct.NewKaitaiInterpreter(schema, logger)
	require.NoError(t, err)

	// Read binary file
	binPath := filepath.Join("../../../test/src", "term_strz.bin")
	binData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse with custom parser
	stream := kaitai.NewStream(bytes.NewReader(binData))
	parsed, err := interpreter.Parse(context.Background(), stream)
	require.NoError(t, err)

	// Convert to map for assertions
	customMap := kaitaistruct.ParsedDataToMap(parsed).(map[string]any)

	// Assertions from KSC test

	// Assert BytesTerm
	if bytesterm_val, ok := customMap["BytesTerm"]; ok {
		assert.EqualValues(t, []uint8{102, 111, 111}, bytesterm_val)
	} else {
		t.Fatalf("Field 'BytesTerm' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert BytesLimit
	if byteslimit_val, ok := customMap["BytesLimit"]; ok {
		assert.EqualValues(t, []uint8{98, 97, 114, 124}, byteslimit_val)
	} else {
		t.Fatalf("Field 'BytesLimit' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert BytesEos
	if byteseos_val, ok := customMap["BytesEos"]; ok {
		assert.EqualValues(t, []uint8{98, 97, 122, 64}, byteseos_val)
	} else {
		t.Fatalf("Field 'BytesEos' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert BytesCalc
	if bytescalc_val, ok := customMap["BytesCalc"]; ok {
		assert.EqualValues(t, []uint8{82, 110, 68}, bytescalc_val)
	} else {
		t.Fatalf("Field 'BytesCalc' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert TermOrLimit
	if termorlimit_val, ok := customMap["TermOrLimit"]; ok {
		assert.EqualValues(t, []uint8{102, 111, 111}, termorlimit_val)
	} else {
		t.Fatalf("Field 'TermOrLimit' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert TermOrEos
	if termoreos_val, ok := customMap["TermOrEos"]; ok {
		assert.EqualValues(t, []uint8{98, 97, 122, 64}, termoreos_val)
	} else {
		t.Fatalf("Field 'TermOrEos' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert TermOrCalc
	if termorcalc_val, ok := customMap["TermOrCalc"]; ok {
		assert.EqualValues(t, []uint8{102, 111, 111}, termorcalc_val)
	} else {
		t.Fatalf("Field 'TermOrCalc' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert LimitOrEos
	if limitoreos_val, ok := customMap["LimitOrEos"]; ok {
		assert.EqualValues(t, []uint8{98, 97, 114, 124}, limitoreos_val)
	} else {
		t.Fatalf("Field 'LimitOrEos' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert LimitOrCalc
	if limitorcalc_val, ok := customMap["LimitOrCalc"]; ok {
		assert.EqualValues(t, []uint8{82, 110, 68}, limitorcalc_val)
	} else {
		t.Fatalf("Field 'LimitOrCalc' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert EosOrCalc
	if eosorcalc_val, ok := customMap["EosOrCalc"]; ok {
		assert.EqualValues(t, []uint8{98, 97, 122, 64}, eosorcalc_val)
	} else {
		t.Fatalf("Field 'EosOrCalc' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

}

func TestSerialize_CombineBytes(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "combine_bytes.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)

	serializer, err := kaitaistruct.NewKaitaiSerializer(schema, nil)
	require.NoError(t, err)

	// Read original binary
	binPath := filepath.Join("../../../test/src", "term_strz.bin")
	originalData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse original
	stream := kaitai.NewStream(bytes.NewReader(originalData))
	original := combine_bytes_kaitai.NewCombineBytes()
	err = original.Read(stream, original, original)
	require.NoError(t, err)

	// Serialize and verify round-trip
	inputMap := structToMapCombineBytes(t, original)

	serialized, err := serializer.Serialize(context.Background(), inputMap)
	require.NoError(t, err)

	// Parse serialized data
	stream2 := kaitai.NewStream(bytes.NewReader(serialized))
	reparsed := combine_bytes_kaitai.NewCombineBytes()
	err = reparsed.Read(stream2, reparsed, reparsed)
	require.NoError(t, err)

	// Compare structures with Phase 2/3 enhanced comparison
	cmpOpts := []cmp.Option{
		cmpopts.IgnoreUnexported(
			kaitai.Stream{},
		),
		cmpopts.IgnoreFields(combine_bytes_kaitai.CombineBytes{}, "_io", "_parent", "_root"),
		cmpopts.EquateEmpty(),
	}
	if diff := cmp.Diff(original, reparsed, cmpOpts...); diff != "" {
		t.Errorf("Serialization mismatch (-original +reparsed):\n%s", diff)
	}
}

// structToMapCombineBytes converts KSC struct to map for serializer
func structToMapCombineBytes(t *testing.T, data any) map[string]any {
	// Use reflection to handle KSC structs with method-based values
	return structToMapReflectiveCombineBytes(t, data)
}

// structToMapReflectiveCombineBytes uses reflection to convert KSC structs including method calls
func structToMapReflectiveCombineBytes(t *testing.T, data any) map[string]any {
	result := make(map[string]any)

	val := reflect.ValueOf(data)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	typ := val.Type()

	// Process fields
	for i := 0; i < val.NumField(); i++ {
		field := typ.Field(i)
		fieldVal := val.Field(i)

		// Skip internal KSC fields
		if strings.HasPrefix(field.Name, "_") {
			continue
		}

		fieldName := strings.ToLower(field.Name)

		if !fieldVal.IsValid() || fieldVal.IsZero() {
			continue
		}

		// Handle different field types
		switch fieldVal.Kind() {
		case reflect.Ptr:
			if !fieldVal.IsNil() {
				// For custom types, check for AsInt/AsStr methods
				subResult := make(map[string]any)

				// Try to call AsInt method
				if method := fieldVal.MethodByName("AsInt"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asint"] = results[0].Interface()
					}
				}

				// Try to call AsStr method
				if method := fieldVal.MethodByName("AsStr"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asstr"] = results[0].Interface()
					}
				}

				// Also include raw fields
				subMap := structToMapReflectiveCombineBytes(t, fieldVal.Interface())
				for k, v := range subMap {
					if _, exists := subResult[k]; !exists {
						subResult[k] = v
					}
				}

				result[fieldName] = subResult
			}
		case reflect.Slice:
			if fieldVal.Len() > 0 {
				slice := make([]any, fieldVal.Len())
				for j := 0; j < fieldVal.Len(); j++ {
					slice[j] = fieldVal.Index(j).Interface()
				}
				result[fieldName] = slice
			}
		default:
			result[fieldName] = fieldVal.Interface()
		}
	}

	return result
}
