// Code generated by kaitai-test-gen-simple.go; DO NOT EDIT.
package formats_test

import (
	"bytes"
	"context"
	"log/slog"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/twinfer/kbin-plugin/pkg/kaitaistruct"
	combine_str_kaitai "github.com/twinfer/kbin-plugin/testdata/formats_kaitai_go_gen/combine_str"
)

func TestParse_CombineStr(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "combine_str.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)
	logger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug}))
	interpreter, err := kaitaistruct.NewKaitaiInterpreter(schema, logger)
	require.NoError(t, err)

	// Read binary file
	binPath := filepath.Join("../../../test/src", "term_strz.bin")
	binData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse with custom parser
	stream := kaitai.NewStream(bytes.NewReader(binData))
	parsed, err := interpreter.Parse(context.Background(), stream)
	require.NoError(t, err)

	// Convert to map for assertions
	customMap := kaitaistruct.ParsedDataToMap(parsed).(map[string]any)

	// Assertions from KSC test

	// Assert StrTerm
	if strterm_val, ok := customMap["StrTerm"]; ok {
		assert.EqualValues(t, "foo", strterm_val)
	} else {
		t.Fatalf("Field 'StrTerm' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert StrLimit
	if strlimit_val, ok := customMap["StrLimit"]; ok {
		assert.EqualValues(t, "bar|", strlimit_val)
	} else {
		t.Fatalf("Field 'StrLimit' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert StrEos
	if streos_val, ok := customMap["StrEos"]; ok {
		assert.EqualValues(t, "baz@", streos_val)
	} else {
		t.Fatalf("Field 'StrEos' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert StrCalc
	if strcalc_val, ok := customMap["StrCalc"]; ok {
		assert.EqualValues(t, "bar", strcalc_val)
	} else {
		t.Fatalf("Field 'StrCalc' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert StrCalcBytes
	if strcalcbytes_val, ok := customMap["StrCalcBytes"]; ok {
		assert.EqualValues(t, "baz", strcalcbytes_val)
	} else {
		t.Fatalf("Field 'StrCalcBytes' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert TermOrLimit
	if termorlimit_val, ok := customMap["TermOrLimit"]; ok {
		assert.EqualValues(t, "foo", termorlimit_val)
	} else {
		t.Fatalf("Field 'TermOrLimit' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert TermOrEos
	if termoreos_val, ok := customMap["TermOrEos"]; ok {
		assert.EqualValues(t, "baz@", termoreos_val)
	} else {
		t.Fatalf("Field 'TermOrEos' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert TermOrCalc
	if termorcalc_val, ok := customMap["TermOrCalc"]; ok {
		assert.EqualValues(t, "foo", termorcalc_val)
	} else {
		t.Fatalf("Field 'TermOrCalc' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert TermOrCalcBytes
	if termorcalcbytes_val, ok := customMap["TermOrCalcBytes"]; ok {
		assert.EqualValues(t, "baz", termorcalcbytes_val)
	} else {
		t.Fatalf("Field 'TermOrCalcBytes' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert LimitOrEos
	if limitoreos_val, ok := customMap["LimitOrEos"]; ok {
		assert.EqualValues(t, "bar|", limitoreos_val)
	} else {
		t.Fatalf("Field 'LimitOrEos' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert LimitOrCalc
	if limitorcalc_val, ok := customMap["LimitOrCalc"]; ok {
		assert.EqualValues(t, "bar", limitorcalc_val)
	} else {
		t.Fatalf("Field 'LimitOrCalc' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert LimitOrCalcBytes
	if limitorcalcbytes_val, ok := customMap["LimitOrCalcBytes"]; ok {
		assert.EqualValues(t, "bar|", limitorcalcbytes_val)
	} else {
		t.Fatalf("Field 'LimitOrCalcBytes' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert EosOrCalc
	if eosorcalc_val, ok := customMap["EosOrCalc"]; ok {
		assert.EqualValues(t, "bar", eosorcalc_val)
	} else {
		t.Fatalf("Field 'EosOrCalc' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert EosOrCalcBytes
	if eosorcalcbytes_val, ok := customMap["EosOrCalcBytes"]; ok {
		assert.EqualValues(t, "baz@", eosorcalcbytes_val)
	} else {
		t.Fatalf("Field 'EosOrCalcBytes' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert CalcOrCalcBytes
	if calcorcalcbytes_val, ok := customMap["CalcOrCalcBytes"]; ok {
		assert.EqualValues(t, "baz", calcorcalcbytes_val)
	} else {
		t.Fatalf("Field 'CalcOrCalcBytes' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

}

func TestSerialize_CombineStr(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "combine_str.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)

	serializer, err := kaitaistruct.NewKaitaiSerializer(schema, nil)
	require.NoError(t, err)

	// Read original binary
	binPath := filepath.Join("../../../test/src", "term_strz.bin")
	originalData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse original
	stream := kaitai.NewStream(bytes.NewReader(originalData))
	original := combine_str_kaitai.NewCombineStr()
	err = original.Read(stream, original, original)
	require.NoError(t, err)

	// Serialize and verify round-trip
	inputMap := structToMapCombineStr(t, original)

	serialized, err := serializer.Serialize(context.Background(), inputMap)
	require.NoError(t, err)

	// Parse serialized data
	stream2 := kaitai.NewStream(bytes.NewReader(serialized))
	reparsed := combine_str_kaitai.NewCombineStr()
	err = reparsed.Read(stream2, reparsed, reparsed)
	require.NoError(t, err)

	// Compare structures with Phase 2/3 enhanced comparison
	cmpOpts := []cmp.Option{
		cmpopts.IgnoreUnexported(
			kaitai.Stream{},
		),
		cmpopts.IgnoreFields(combine_str_kaitai.CombineStr{}, "_io", "_parent", "_root"),
		cmpopts.EquateEmpty(),
	}
	if diff := cmp.Diff(original, reparsed, cmpOpts...); diff != "" {
		t.Errorf("Serialization mismatch (-original +reparsed):\n%s", diff)
	}
}

// structToMapCombineStr converts KSC struct to map for serializer
func structToMapCombineStr(t *testing.T, data any) map[string]any {
	// Use reflection to handle KSC structs with method-based values
	return structToMapReflectiveCombineStr(t, data)
}

// structToMapReflectiveCombineStr uses reflection to convert KSC structs including method calls
func structToMapReflectiveCombineStr(t *testing.T, data any) map[string]any {
	result := make(map[string]any)

	val := reflect.ValueOf(data)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	typ := val.Type()

	// Process fields
	for i := 0; i < val.NumField(); i++ {
		field := typ.Field(i)
		fieldVal := val.Field(i)

		// Skip internal KSC fields
		if strings.HasPrefix(field.Name, "_") {
			continue
		}

		fieldName := strings.ToLower(field.Name)

		if !fieldVal.IsValid() || fieldVal.IsZero() {
			continue
		}

		// Handle different field types
		switch fieldVal.Kind() {
		case reflect.Ptr:
			if !fieldVal.IsNil() {
				// For custom types, check for AsInt/AsStr methods
				subResult := make(map[string]any)

				// Try to call AsInt method
				if method := fieldVal.MethodByName("AsInt"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asint"] = results[0].Interface()
					}
				}

				// Try to call AsStr method
				if method := fieldVal.MethodByName("AsStr"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asstr"] = results[0].Interface()
					}
				}

				// Also include raw fields
				subMap := structToMapReflectiveCombineStr(t, fieldVal.Interface())
				for k, v := range subMap {
					if _, exists := subResult[k]; !exists {
						subResult[k] = v
					}
				}

				result[fieldName] = subResult
			}
		case reflect.Slice:
			if fieldVal.Len() > 0 {
				slice := make([]any, fieldVal.Len())
				for j := 0; j < fieldVal.Len(); j++ {
					slice[j] = fieldVal.Index(j).Interface()
				}
				result[fieldName] = slice
			}
		default:
			result[fieldName] = fieldVal.Interface()
		}
	}

	return result
}
