// Code generated by kaitai-test-gen-simple.go; DO NOT EDIT.
package formats_test

import (
	"bytes"
	"context"
	"log/slog"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/twinfer/kbin-plugin/pkg/kaitaistruct"
	debug_enum_name_kaitai "github.com/twinfer/kbin-plugin/testdata/formats_kaitai_go_gen/debug_enum_name"
)

func TestParse_DebugEnumName(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "debug_enum_name.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)
	logger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug}))
	interpreter, err := kaitaistruct.NewKaitaiInterpreter(schema, logger)
	require.NoError(t, err)

	// Read binary file
	binPath := filepath.Join("../../../test/src", "fixed_struct.bin")
	binData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse with custom parser
	stream := kaitai.NewStream(bytes.NewReader(binData))
	parsed, err := interpreter.Parse(context.Background(), stream)
	require.NoError(t, err)

	// Convert to map for assertions
	customMap := kaitaistruct.ParsedDataToMap(parsed).(map[string]any)

	// Assertions from KSC test

	// Assert One
	if one_val, ok := customMap["One"]; ok {
		assert.EqualValues(t, DebugEnumName_TestEnum1__EnumValue80, one_val)
	} else {
		t.Fatalf("Field 'One' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert TestType.Field1
	if testtype_field1_lvl0_map, ok := customMap["TestType"].(map[string]any); ok {
		if testtype_field1_val, ok := testtype_field1_lvl0_map["Field1"]; ok {
			assert.EqualValues(t, DebugEnumName_TestSubtype_InnerEnum1__EnumValue67, testtype_field1_val)
		} else {
			t.Fatalf("Field 'Field1' not found in testtype_field1_lvl0_map (keys: %v)", maps.Keys(testtype_field1_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'TestType' not found or not a map while asserting TestType.Field1")
	}

	// Assert TestType.InstanceField
	if testtype_instancefield_lvl0_map, ok := customMap["TestType"].(map[string]any); ok {
		if testtype_instancefield_val, ok := testtype_instancefield_lvl0_map["InstanceField"]; ok {
			assert.EqualValues(t, DebugEnumName_TestSubtype_InnerEnum2__EnumValue11, testtype_instancefield_val)
		} else {
			t.Fatalf("Field 'InstanceField' not found in testtype_instancefield_lvl0_map (keys: %v)", maps.Keys(testtype_instancefield_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'TestType' not found or not a map while asserting TestType.InstanceField")
	}

}

func TestSerialize_DebugEnumName(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "debug_enum_name.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)

	serializer, err := kaitaistruct.NewKaitaiSerializer(schema, nil)
	require.NoError(t, err)

	// Read original binary
	binPath := filepath.Join("../../../test/src", "fixed_struct.bin")
	originalData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse original
	stream := kaitai.NewStream(bytes.NewReader(originalData))
	original := debug_enum_name_kaitai.NewDebugEnumName()
	err = original.Read(stream, original, original)
	require.NoError(t, err)

	// Serialize and verify round-trip
	inputMap := structToMapDebugEnumName(t, original)

	serialized, err := serializer.Serialize(context.Background(), inputMap)
	require.NoError(t, err)

	// Parse serialized data
	stream2 := kaitai.NewStream(bytes.NewReader(serialized))
	reparsed := debug_enum_name_kaitai.NewDebugEnumName()
	err = reparsed.Read(stream2, reparsed, reparsed)
	require.NoError(t, err)

	// Compare structures with Phase 2/3 enhanced comparison
	cmpOpts := []cmp.Option{
		cmpopts.IgnoreUnexported(
			kaitai.Stream{},
		),
		cmpopts.IgnoreFields(debug_enum_name_kaitai.DebugEnumName{}, "_io", "_parent", "_root"),
		cmpopts.EquateEmpty(),
	}
	if diff := cmp.Diff(original, reparsed, cmpOpts...); diff != "" {
		t.Errorf("Serialization mismatch (-original +reparsed):\n%s", diff)
	}
}

// structToMapDebugEnumName converts KSC struct to map for serializer
func structToMapDebugEnumName(t *testing.T, data any) map[string]any {
	// Use reflection to handle KSC structs with method-based values
	return structToMapReflectiveDebugEnumName(t, data)
}

// structToMapReflectiveDebugEnumName uses reflection to convert KSC structs including method calls
func structToMapReflectiveDebugEnumName(t *testing.T, data any) map[string]any {
	result := make(map[string]any)

	val := reflect.ValueOf(data)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	typ := val.Type()

	// Process fields
	for i := 0; i < val.NumField(); i++ {
		field := typ.Field(i)
		fieldVal := val.Field(i)

		// Skip internal KSC fields
		if strings.HasPrefix(field.Name, "_") {
			continue
		}

		fieldName := strings.ToLower(field.Name)

		if !fieldVal.IsValid() || fieldVal.IsZero() {
			continue
		}

		// Handle different field types
		switch fieldVal.Kind() {
		case reflect.Ptr:
			if !fieldVal.IsNil() {
				// For custom types, check for AsInt/AsStr methods
				subResult := make(map[string]any)

				// Try to call AsInt method
				if method := fieldVal.MethodByName("AsInt"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asint"] = results[0].Interface()
					}
				}

				// Try to call AsStr method
				if method := fieldVal.MethodByName("AsStr"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asstr"] = results[0].Interface()
					}
				}

				// Also include raw fields
				subMap := structToMapReflectiveDebugEnumName(t, fieldVal.Interface())
				for k, v := range subMap {
					if _, exists := subResult[k]; !exists {
						subResult[k] = v
					}
				}

				result[fieldName] = subResult
			}
		case reflect.Slice:
			if fieldVal.Len() > 0 {
				slice := make([]any, fieldVal.Len())
				for j := 0; j < fieldVal.Len(); j++ {
					slice[j] = fieldVal.Index(j).Interface()
				}
				result[fieldName] = slice
			}
		default:
			result[fieldName] = fieldVal.Interface()
		}
	}

	return result
}
