// Code generated by kaitai-test-gen-simple.go; DO NOT EDIT.
package formats_test

import (
	"bytes"
	"context"
	"log/slog"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/twinfer/kbin-plugin/pkg/kaitaistruct"
	enum_long_range_s_kaitai "github.com/twinfer/kbin-plugin/testdata/formats_kaitai_go_gen/enum_long_range_s"
)

func TestParse_EnumLongRangeS(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "enum_long_range_s.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)
	logger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug}))
	interpreter, err := kaitaistruct.NewKaitaiInterpreter(schema, logger)
	require.NoError(t, err)

	// Read binary file
	binPath := filepath.Join("../../../test/src", "enum_long_range_s.bin")
	binData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse with custom parser
	stream := kaitai.NewStream(bytes.NewReader(binData))
	parsed, err := interpreter.Parse(context.Background(), stream)
	require.NoError(t, err)

	// Convert to map for assertions
	customMap := kaitaistruct.ParsedDataToMap(parsed).(map[string]any)

	// Assertions from KSC test

	// Assert F1
	if f1_val, ok := customMap["F1"]; ok {
		assert.EqualValues(t, EnumLongRangeS_Constants__LongMin, f1_val)
	} else {
		t.Fatalf("Field 'F1' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert F2
	if f2_val, ok := customMap["F2"]; ok {
		assert.EqualValues(t, EnumLongRangeS_Constants__IntBelowMin, f2_val)
	} else {
		t.Fatalf("Field 'F2' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert F3
	if f3_val, ok := customMap["F3"]; ok {
		assert.EqualValues(t, EnumLongRangeS_Constants__IntMin, f3_val)
	} else {
		t.Fatalf("Field 'F3' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert F4
	if f4_val, ok := customMap["F4"]; ok {
		assert.EqualValues(t, EnumLongRangeS_Constants__Zero, f4_val)
	} else {
		t.Fatalf("Field 'F4' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert F5
	if f5_val, ok := customMap["F5"]; ok {
		assert.EqualValues(t, EnumLongRangeS_Constants__IntMax, f5_val)
	} else {
		t.Fatalf("Field 'F5' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert F6
	if f6_val, ok := customMap["F6"]; ok {
		assert.EqualValues(t, EnumLongRangeS_Constants__IntOverMax, f6_val)
	} else {
		t.Fatalf("Field 'F6' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert F7
	if f7_val, ok := customMap["F7"]; ok {
		assert.EqualValues(t, EnumLongRangeS_Constants__LongMax, f7_val)
	} else {
		t.Fatalf("Field 'F7' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

}

func TestSerialize_EnumLongRangeS(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "enum_long_range_s.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)

	serializer, err := kaitaistruct.NewKaitaiSerializer(schema, nil)
	require.NoError(t, err)

	// Read original binary
	binPath := filepath.Join("../../../test/src", "enum_long_range_s.bin")
	originalData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse original
	stream := kaitai.NewStream(bytes.NewReader(originalData))
	original := enum_long_range_s_kaitai.NewEnumLongRangeS()
	err = original.Read(stream, original, original)
	require.NoError(t, err)

	// Serialize and verify round-trip
	inputMap := structToMapEnumLongRangeS(t, original)

	serialized, err := serializer.Serialize(context.Background(), inputMap)
	require.NoError(t, err)

	// Parse serialized data
	stream2 := kaitai.NewStream(bytes.NewReader(serialized))
	reparsed := enum_long_range_s_kaitai.NewEnumLongRangeS()
	err = reparsed.Read(stream2, reparsed, reparsed)
	require.NoError(t, err)

	// Compare structures with Phase 2/3 enhanced comparison
	cmpOpts := []cmp.Option{
		cmpopts.IgnoreUnexported(
			kaitai.Stream{},
		),
		cmpopts.IgnoreFields(enum_long_range_s_kaitai.EnumLongRangeS{}, "_io", "_parent", "_root"),
		cmpopts.EquateEmpty(),
	}
	if diff := cmp.Diff(original, reparsed, cmpOpts...); diff != "" {
		t.Errorf("Serialization mismatch (-original +reparsed):\n%s", diff)
	}
}

// structToMapEnumLongRangeS converts KSC struct to map for serializer
func structToMapEnumLongRangeS(t *testing.T, data any) map[string]any {
	// Use reflection to handle KSC structs with method-based values
	return structToMapReflectiveEnumLongRangeS(t, data)
}

// structToMapReflectiveEnumLongRangeS uses reflection to convert KSC structs including method calls
func structToMapReflectiveEnumLongRangeS(t *testing.T, data any) map[string]any {
	result := make(map[string]any)

	val := reflect.ValueOf(data)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	typ := val.Type()

	// Process fields
	for i := 0; i < val.NumField(); i++ {
		field := typ.Field(i)
		fieldVal := val.Field(i)

		// Skip internal KSC fields
		if strings.HasPrefix(field.Name, "_") {
			continue
		}

		fieldName := strings.ToLower(field.Name)

		if !fieldVal.IsValid() || fieldVal.IsZero() {
			continue
		}

		// Handle different field types
		switch fieldVal.Kind() {
		case reflect.Ptr:
			if !fieldVal.IsNil() {
				// For custom types, check for AsInt/AsStr methods
				subResult := make(map[string]any)

				// Try to call AsInt method
				if method := fieldVal.MethodByName("AsInt"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asint"] = results[0].Interface()
					}
				}

				// Try to call AsStr method
				if method := fieldVal.MethodByName("AsStr"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asstr"] = results[0].Interface()
					}
				}

				// Also include raw fields
				subMap := structToMapReflectiveEnumLongRangeS(t, fieldVal.Interface())
				for k, v := range subMap {
					if _, exists := subResult[k]; !exists {
						subResult[k] = v
					}
				}

				result[fieldName] = subResult
			}
		case reflect.Slice:
			if fieldVal.Len() > 0 {
				slice := make([]any, fieldVal.Len())
				for j := 0; j < fieldVal.Len(); j++ {
					slice[j] = fieldVal.Index(j).Interface()
				}
				result[fieldName] = slice
			}
		default:
			result[fieldName] = fieldVal.Interface()
		}
	}

	return result
}
