// Code generated by kaitai-test-gen-simple.go; DO NOT EDIT.
package formats_test

import (
	"bytes"
	"context"
	"io"
	"log/slog"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/twinfer/kbin-plugin/pkg/kaitaistruct"
	expr_2_kaitai "github.com/twinfer/kbin-plugin/testdata/formats_kaitai_go_gen/expr_2"
)

func TestParse_Expr2(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "expr_2.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)
	logger := slog.New(slog.NewTextHandler(io.Discard, nil))
	interpreter, err := kaitaistruct.NewKaitaiInterpreter(schema, logger)
	require.NoError(t, err)

	// Read binary file
	binPath := filepath.Join("../../../test/src", "str_encodings.bin")
	binData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse with custom parser
	stream := kaitai.NewStream(bytes.NewReader(binData))
	parsed, err := interpreter.Parse(context.Background(), stream)
	require.NoError(t, err)

	// Convert to map for assertions
	customMap := kaitaistruct.ParsedDataToMap(parsed).(map[string]any)

	// Assertions from KSC test

	// Assert Str1.LenOrig
	if str1_len_orig_lvl0_map, ok := customMap["str1"].(map[string]any); ok {
		if str1_len_orig_val, ok := str1_len_orig_lvl0_map["len_orig"]; ok {
			assert.EqualValues(t, 10, str1_len_orig_val)
		} else {
			t.Fatalf("Field 'len_orig' not found in str1_len_orig_lvl0_map (keys: %v)", maps.Keys(str1_len_orig_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'str1' not found or not a map while asserting Str1.LenOrig")
	}

	// Assert Str1.LenMod
	if str1_len_mod_lvl0_map, ok := customMap["str1"].(map[string]any); ok {
		if str1_len_mod_val, ok := str1_len_mod_lvl0_map["len_mod"]; ok {
			assert.EqualValues(t, 7, str1_len_mod_val)
		} else {
			t.Fatalf("Field 'len_mod' not found in str1_len_mod_lvl0_map (keys: %v)", maps.Keys(str1_len_mod_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'str1' not found or not a map while asserting Str1.LenMod")
	}

	// Assert Str1.Str
	if str1_str_lvl0_map, ok := customMap["str1"].(map[string]any); ok {
		if str1_str_val, ok := str1_str_lvl0_map["str"]; ok {
			assert.EqualValues(t, "Some AS", str1_str_val)
		} else {
			t.Fatalf("Field 'str' not found in str1_str_lvl0_map (keys: %v)", maps.Keys(str1_str_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'str1' not found or not a map while asserting Str1.Str")
	}

	// Assert Str1Len
	if str1len_val, ok := customMap["str1len"]; ok {
		assert.EqualValues(t, 7, str1len_val)
	} else {
		t.Fatalf("Field 'str1len' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Str1LenMod
	if str1len_mod_val, ok := customMap["str1len_mod"]; ok {
		assert.EqualValues(t, 7, str1len_mod_val)
	} else {
		t.Fatalf("Field 'str1len_mod' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Str1Byte1
	if str1byte1_val, ok := customMap["str1byte1"]; ok {
		assert.EqualValues(t, 73, str1byte1_val)
	} else {
		t.Fatalf("Field 'str1byte1' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Str1Avg
	if str1avg_val, ok := customMap["str1avg"]; ok {
		assert.EqualValues(t, 73, str1avg_val)
	} else {
		t.Fatalf("Field 'str1avg' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Str1Char5
	if str1char5_val, ok := customMap["str1char5"]; ok {
		assert.EqualValues(t, "e", str1char5_val)
	} else {
		t.Fatalf("Field 'str1char5' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert tmp7.Byte0
	if tmp7_byte0_lvl0_map, ok := customMap["tmp7"].(map[string]any); ok {
		if tmp7_byte0_val, ok := tmp7_byte0_lvl0_map["byte0"]; ok {
			assert.EqualValues(t, 101, tmp7_byte0_val)
		} else {
			t.Fatalf("Field 'byte0' not found in tmp7_byte0_lvl0_map (keys: %v)", maps.Keys(tmp7_byte0_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'tmp7' not found or not a map while asserting tmp7.Byte0")
	}

	// Assert tmp8.Byte0
	if tmp8_byte0_lvl0_map, ok := customMap["tmp8"].(map[string]any); ok {
		if tmp8_byte0_val, ok := tmp8_byte0_lvl0_map["byte0"]; ok {
			assert.EqualValues(t, 101, tmp8_byte0_val)
		} else {
			t.Fatalf("Field 'byte0' not found in tmp8_byte0_lvl0_map (keys: %v)", maps.Keys(tmp8_byte0_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'tmp8' not found or not a map while asserting tmp8.Byte0")
	}

	// Assert tmp9.Byte1
	if tmp9_byte_1_lvl0_map, ok := customMap["tmp9"].(map[string]any); ok {
		if tmp9_byte_1_val, ok := tmp9_byte_1_lvl0_map["byte_1"]; ok {
			assert.EqualValues(t, 32, tmp9_byte_1_val)
		} else {
			t.Fatalf("Field 'byte_1' not found in tmp9_byte_1_lvl0_map (keys: %v)", maps.Keys(tmp9_byte_1_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'tmp9' not found or not a map while asserting tmp9.Byte1")
	}

	// Assert tmp10.Byte2
	if tmp10_byte_2_lvl0_map, ok := customMap["tmp10"].(map[string]any); ok {
		if tmp10_byte_2_val, ok := tmp10_byte_2_lvl0_map["byte_2"]; ok {
			assert.EqualValues(t, 65, tmp10_byte_2_val)
		} else {
			t.Fatalf("Field 'byte_2' not found in tmp10_byte_2_lvl0_map (keys: %v)", maps.Keys(tmp10_byte_2_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'tmp10' not found or not a map while asserting tmp10.Byte2")
	}

	// Assert tmp11.Avg
	if tmp11_avg_lvl0_map, ok := customMap["tmp11"].(map[string]any); ok {
		if tmp11_avg_val, ok := tmp11_avg_lvl0_map["avg"]; ok {
			assert.EqualValues(t, 48, tmp11_avg_val)
		} else {
			t.Fatalf("Field 'avg' not found in tmp11_avg_lvl0_map (keys: %v)", maps.Keys(tmp11_avg_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'tmp11' not found or not a map while asserting tmp11.Avg")
	}

	// Assert tmp13.Byte0
	if tmp13_byte0_lvl0_map, ok := customMap["tmp13"].(map[string]any); ok {
		if tmp13_byte0_val, ok := tmp13_byte0_lvl0_map["byte0"]; ok {
			assert.EqualValues(t, 101, tmp13_byte0_val)
		} else {
			t.Fatalf("Field 'byte0' not found in tmp13_byte0_lvl0_map (keys: %v)", maps.Keys(tmp13_byte0_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'tmp13' not found or not a map while asserting tmp13.Byte0")
	}

	// Assert tmp14.Byte1
	if tmp14_byte_1_lvl0_map, ok := customMap["tmp14"].(map[string]any); ok {
		if tmp14_byte_1_val, ok := tmp14_byte_1_lvl0_map["byte_1"]; ok {
			assert.EqualValues(t, 32, tmp14_byte_1_val)
		} else {
			t.Fatalf("Field 'byte_1' not found in tmp14_byte_1_lvl0_map (keys: %v)", maps.Keys(tmp14_byte_1_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'tmp14' not found or not a map while asserting tmp14.Byte1")
	}

	// Assert tmp15.Byte2
	if tmp15_byte_2_lvl0_map, ok := customMap["tmp15"].(map[string]any); ok {
		if tmp15_byte_2_val, ok := tmp15_byte_2_lvl0_map["byte_2"]; ok {
			assert.EqualValues(t, 65, tmp15_byte_2_val)
		} else {
			t.Fatalf("Field 'byte_2' not found in tmp15_byte_2_lvl0_map (keys: %v)", maps.Keys(tmp15_byte_2_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'tmp15' not found or not a map while asserting tmp15.Byte2")
	}

	// Assert tmp16.Avg
	if tmp16_avg_lvl0_map, ok := customMap["tmp16"].(map[string]any); ok {
		if tmp16_avg_val, ok := tmp16_avg_lvl0_map["avg"]; ok {
			assert.EqualValues(t, 48, tmp16_avg_val)
		} else {
			t.Fatalf("Field 'avg' not found in tmp16_avg_lvl0_map (keys: %v)", maps.Keys(tmp16_avg_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'tmp16' not found or not a map while asserting tmp16.Avg")
	}

}

func TestSerialize_Expr2(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "expr_2.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)

	serializer, err := kaitaistruct.NewKaitaiSerializer(schema, nil)
	require.NoError(t, err)

	// Read original binary
	binPath := filepath.Join("../../../test/src", "str_encodings.bin")
	originalData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse original
	stream := kaitai.NewStream(bytes.NewReader(originalData))
	original := expr_2_kaitai.NewExpr2()
	err = original.Read(stream, original, original)
	require.NoError(t, err)

	// Serialize and verify round-trip
	inputMap := structToMapExpr2(t, original)

	serialized, err := serializer.Serialize(context.Background(), inputMap)
	require.NoError(t, err)

	// Parse serialized data
	stream2 := kaitai.NewStream(bytes.NewReader(serialized))
	reparsed := expr_2_kaitai.NewExpr2()
	err = reparsed.Read(stream2, reparsed, reparsed)
	require.NoError(t, err)

	// Compare structures with Phase 2/3 enhanced comparison
	cmpOpts := []cmp.Option{
		cmpopts.IgnoreUnexported(
			kaitai.Stream{},
		),
		cmpopts.IgnoreFields(expr_2_kaitai.Expr2{}, "_io", "_parent", "_root"),
		cmpopts.EquateEmpty(),
	}
	if diff := cmp.Diff(original, reparsed, cmpOpts...); diff != "" {
		t.Errorf("Serialization mismatch (-original +reparsed):\n%s", diff)
	}
}

// structToMapExpr2 converts KSC struct to map for serializer
func structToMapExpr2(t *testing.T, data any) map[string]any {
	// Use reflection to handle KSC structs with method-based values
	return structToMapReflectiveExpr2(t, data)
}

// structToMapReflectiveExpr2 uses reflection to convert KSC structs including method calls
func structToMapReflectiveExpr2(t *testing.T, data any) map[string]any {
	result := make(map[string]any)

	val := reflect.ValueOf(data)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	typ := val.Type()

	// Process fields
	for i := 0; i < val.NumField(); i++ {
		field := typ.Field(i)
		fieldVal := val.Field(i)

		// Skip internal KSC fields
		if strings.HasPrefix(field.Name, "_") {
			continue
		}

		fieldName := strings.ToLower(field.Name)

		if !fieldVal.IsValid() || fieldVal.IsZero() {
			continue
		}

		// Handle different field types
		switch fieldVal.Kind() {
		case reflect.Ptr:
			if !fieldVal.IsNil() {
				// For custom types, check for AsInt/AsStr methods
				subResult := make(map[string]any)

				// Try to call AsInt method
				if method := fieldVal.MethodByName("AsInt"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asint"] = results[0].Interface()
					}
				}

				// Try to call AsStr method
				if method := fieldVal.MethodByName("AsStr"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asstr"] = results[0].Interface()
					}
				}

				// Also include raw fields
				subMap := structToMapReflectiveExpr2(t, fieldVal.Interface())
				for k, v := range subMap {
					if _, exists := subResult[k]; !exists {
						subResult[k] = v
					}
				}

				result[fieldName] = subResult
			}
		case reflect.Slice:
			if fieldVal.Len() > 0 {
				slice := make([]any, fieldVal.Len())
				for j := 0; j < fieldVal.Len(); j++ {
					slice[j] = fieldVal.Index(j).Interface()
				}
				result[fieldName] = slice
			}
		default:
			result[fieldName] = fieldVal.Interface()
		}
	}

	return result
}
