// Code generated by kaitai-test-gen-simple.go; DO NOT EDIT.
package formats_test

import (
	"bytes"
	"context"
	"io"
	"log/slog"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/twinfer/kbin-plugin/pkg/kaitaistruct"
	expr_mod_kaitai "github.com/twinfer/kbin-plugin/testdata/formats_kaitai_go_gen/expr_mod"
)

func TestParse_ExprMod(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "expr_mod.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)
	logger := slog.New(slog.NewTextHandler(io.Discard, nil))
	interpreter, err := kaitaistruct.NewKaitaiInterpreter(schema, logger)
	require.NoError(t, err)

	// Read binary file
	binPath := filepath.Join("../../../test/src", "fixed_struct.bin")
	binData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse with custom parser
	stream := kaitai.NewStream(bytes.NewReader(binData))
	parsed, err := interpreter.Parse(context.Background(), stream)
	require.NoError(t, err)

	// Convert to map for assertions
	customMap := kaitaistruct.ParsedDataToMap(parsed).(map[string]any)

	// Assertions from KSC test

	// Assert IntU
	if int_u_val, ok := customMap["int_u"]; ok {
		assert.EqualValues(t, 1262698832, int_u_val)
	} else {
		t.Fatalf("Field 'int_u' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert IntS
	if int_s_val, ok := customMap["int_s"]; ok {
		assert.EqualValues(t, -52947, int_s_val)
	} else {
		t.Fatalf("Field 'int_s' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert ModPosConst
	if mod_pos_const_val, ok := customMap["mod_pos_const"]; ok {
		assert.EqualValues(t, 9, mod_pos_const_val)
	} else {
		t.Fatalf("Field 'mod_pos_const' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert ModNegConst
	if mod_neg_const_val, ok := customMap["mod_neg_const"]; ok {
		assert.EqualValues(t, 4, mod_neg_const_val)
	} else {
		t.Fatalf("Field 'mod_neg_const' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert ModPosSeq
	if mod_pos_seq_val, ok := customMap["mod_pos_seq"]; ok {
		assert.EqualValues(t, 5, mod_pos_seq_val)
	} else {
		t.Fatalf("Field 'mod_pos_seq' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert ModNegSeq
	if mod_neg_seq_val, ok := customMap["mod_neg_seq"]; ok {
		assert.EqualValues(t, 2, mod_neg_seq_val)
	} else {
		t.Fatalf("Field 'mod_neg_seq' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

}

func TestSerialize_ExprMod(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "expr_mod.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)

	serializer, err := kaitaistruct.NewKaitaiSerializer(schema, nil)
	require.NoError(t, err)

	// Read original binary
	binPath := filepath.Join("../../../test/src", "fixed_struct.bin")
	originalData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse original
	stream := kaitai.NewStream(bytes.NewReader(originalData))
	original := expr_mod_kaitai.NewExprMod()
	err = original.Read(stream, original, original)
	require.NoError(t, err)

	// Serialize and verify round-trip
	inputMap := structToMapExprMod(t, original)

	serialized, err := serializer.Serialize(context.Background(), inputMap)
	require.NoError(t, err)

	// Parse serialized data
	stream2 := kaitai.NewStream(bytes.NewReader(serialized))
	reparsed := expr_mod_kaitai.NewExprMod()
	err = reparsed.Read(stream2, reparsed, reparsed)
	require.NoError(t, err)

	// Compare structures with Phase 2/3 enhanced comparison
	cmpOpts := []cmp.Option{
		cmpopts.IgnoreUnexported(
			kaitai.Stream{},
		),
		cmpopts.IgnoreFields(expr_mod_kaitai.ExprMod{}, "_io", "_parent", "_root"),
		cmpopts.EquateEmpty(),
	}
	if diff := cmp.Diff(original, reparsed, cmpOpts...); diff != "" {
		t.Errorf("Serialization mismatch (-original +reparsed):\n%s", diff)
	}
}

// structToMapExprMod converts KSC struct to map for serializer
func structToMapExprMod(t *testing.T, data any) map[string]any {
	// Use reflection to handle KSC structs with method-based values
	return structToMapReflectiveExprMod(t, data)
}

// structToMapReflectiveExprMod uses reflection to convert KSC structs including method calls
func structToMapReflectiveExprMod(t *testing.T, data any) map[string]any {
	result := make(map[string]any)

	val := reflect.ValueOf(data)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	typ := val.Type()

	// Process fields
	for i := 0; i < val.NumField(); i++ {
		field := typ.Field(i)
		fieldVal := val.Field(i)

		// Skip internal KSC fields
		if strings.HasPrefix(field.Name, "_") {
			continue
		}

		fieldName := strings.ToLower(field.Name)

		if !fieldVal.IsValid() || fieldVal.IsZero() {
			continue
		}

		// Handle different field types
		switch fieldVal.Kind() {
		case reflect.Ptr:
			if !fieldVal.IsNil() {
				// For custom types, check for AsInt/AsStr methods
				subResult := make(map[string]any)

				// Try to call AsInt method
				if method := fieldVal.MethodByName("AsInt"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asint"] = results[0].Interface()
					}
				}

				// Try to call AsStr method
				if method := fieldVal.MethodByName("AsStr"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asstr"] = results[0].Interface()
					}
				}

				// Also include raw fields
				subMap := structToMapReflectiveExprMod(t, fieldVal.Interface())
				for k, v := range subMap {
					if _, exists := subResult[k]; !exists {
						subResult[k] = v
					}
				}

				result[fieldName] = subResult
			}
		case reflect.Slice:
			if fieldVal.Len() > 0 {
				slice := make([]any, fieldVal.Len())
				for j := 0; j < fieldVal.Len(); j++ {
					slice[j] = fieldVal.Index(j).Interface()
				}
				result[fieldName] = slice
			}
		default:
			result[fieldName] = fieldVal.Interface()
		}
	}

	return result
}
