// Code generated by kaitai-test-gen-simple.go; DO NOT EDIT.
package formats_test

import (
	"bytes"
	"context"
	"log/slog"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/twinfer/kbin-plugin/pkg/kaitaistruct"
	expr_3_kaitai "github.com/twinfer/kbin-plugin/testdata/formats_kaitai_go_gen/expr_3"
)

func TestParse_Expr3(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "expr_3.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)
	logger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug}))
	interpreter, err := kaitaistruct.NewKaitaiInterpreter(schema, logger)
	require.NoError(t, err)

	// Read binary file
	binPath := filepath.Join("../../../test/src", "fixed_struct.bin")
	binData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse with custom parser
	stream := kaitai.NewStream(bytes.NewReader(binData))
	parsed, err := interpreter.Parse(context.Background(), stream)
	require.NoError(t, err)

	// Convert to map for assertions
	customMap := kaitaistruct.ParsedDataToMap(parsed).(map[string]any)

	// Assertions from KSC test

	// Assert One
	if one_val, ok := customMap["One"]; ok {
		assert.EqualValues(t, 80, one_val)
	} else {
		t.Fatalf("Field 'One' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Two
	if two_val, ok := customMap["Two"]; ok {
		assert.EqualValues(t, "ACK", two_val)
	} else {
		t.Fatalf("Field 'Two' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Three
	if three_val, ok := customMap["Three"]; ok {
		assert.EqualValues(t, "@ACK", three_val)
	} else {
		t.Fatalf("Field 'Three' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Four
	if four_val, ok := customMap["Four"]; ok {
		assert.EqualValues(t, "_ACK_", four_val)
	} else {
		t.Fatalf("Field 'Four' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert IsStrEq
	if isstreq_val, ok := customMap["IsStrEq"]; ok {
		assert.EqualValues(t, true, isstreq_val)
	} else {
		t.Fatalf("Field 'IsStrEq' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert IsStrNe
	if isstrne_val, ok := customMap["IsStrNe"]; ok {
		assert.EqualValues(t, false, isstrne_val)
	} else {
		t.Fatalf("Field 'IsStrNe' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert IsStrLt
	if isstrlt_val, ok := customMap["IsStrLt"]; ok {
		assert.EqualValues(t, true, isstrlt_val)
	} else {
		t.Fatalf("Field 'IsStrLt' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert IsStrGt
	if isstrgt_val, ok := customMap["IsStrGt"]; ok {
		assert.EqualValues(t, false, isstrgt_val)
	} else {
		t.Fatalf("Field 'IsStrGt' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert IsStrLe
	if isstrle_val, ok := customMap["IsStrLe"]; ok {
		assert.EqualValues(t, true, isstrle_val)
	} else {
		t.Fatalf("Field 'IsStrLe' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert IsStrGe
	if isstrge_val, ok := customMap["IsStrGe"]; ok {
		assert.EqualValues(t, false, isstrge_val)
	} else {
		t.Fatalf("Field 'IsStrGe' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert IsStrLt2
	if isstrlt2_val, ok := customMap["IsStrLt2"]; ok {
		assert.EqualValues(t, true, isstrlt2_val)
	} else {
		t.Fatalf("Field 'IsStrLt2' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert TestNot
	if testnot_val, ok := customMap["TestNot"]; ok {
		assert.EqualValues(t, true, testnot_val)
	} else {
		t.Fatalf("Field 'TestNot' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

}

func TestSerialize_Expr3(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "expr_3.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)

	serializer, err := kaitaistruct.NewKaitaiSerializer(schema, nil)
	require.NoError(t, err)

	// Read original binary
	binPath := filepath.Join("../../../test/src", "fixed_struct.bin")
	originalData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse original
	stream := kaitai.NewStream(bytes.NewReader(originalData))
	original := expr_3_kaitai.NewExpr3()
	err = original.Read(stream, original, original)
	require.NoError(t, err)

	// Serialize and verify round-trip
	inputMap := structToMapExpr3(t, original)

	serialized, err := serializer.Serialize(context.Background(), inputMap)
	require.NoError(t, err)

	// Parse serialized data
	stream2 := kaitai.NewStream(bytes.NewReader(serialized))
	reparsed := expr_3_kaitai.NewExpr3()
	err = reparsed.Read(stream2, reparsed, reparsed)
	require.NoError(t, err)

	// Compare structures with Phase 2/3 enhanced comparison
	cmpOpts := []cmp.Option{
		cmpopts.IgnoreUnexported(
			kaitai.Stream{},
		),
		cmpopts.IgnoreFields(expr_3_kaitai.Expr3{}, "_io", "_parent", "_root"),
		cmpopts.EquateEmpty(),
	}
	if diff := cmp.Diff(original, reparsed, cmpOpts...); diff != "" {
		t.Errorf("Serialization mismatch (-original +reparsed):\n%s", diff)
	}
}

// structToMapExpr3 converts KSC struct to map for serializer
func structToMapExpr3(t *testing.T, data any) map[string]any {
	// Use reflection to handle KSC structs with method-based values
	return structToMapReflectiveExpr3(t, data)
}

// structToMapReflectiveExpr3 uses reflection to convert KSC structs including method calls
func structToMapReflectiveExpr3(t *testing.T, data any) map[string]any {
	result := make(map[string]any)

	val := reflect.ValueOf(data)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	typ := val.Type()

	// Process fields
	for i := 0; i < val.NumField(); i++ {
		field := typ.Field(i)
		fieldVal := val.Field(i)

		// Skip internal KSC fields
		if strings.HasPrefix(field.Name, "_") {
			continue
		}

		fieldName := strings.ToLower(field.Name)

		if !fieldVal.IsValid() || fieldVal.IsZero() {
			continue
		}

		// Handle different field types
		switch fieldVal.Kind() {
		case reflect.Ptr:
			if !fieldVal.IsNil() {
				// For custom types, check for AsInt/AsStr methods
				subResult := make(map[string]any)

				// Try to call AsInt method
				if method := fieldVal.MethodByName("AsInt"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asint"] = results[0].Interface()
					}
				}

				// Try to call AsStr method
				if method := fieldVal.MethodByName("AsStr"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asstr"] = results[0].Interface()
					}
				}

				// Also include raw fields
				subMap := structToMapReflectiveExpr3(t, fieldVal.Interface())
				for k, v := range subMap {
					if _, exists := subResult[k]; !exists {
						subResult[k] = v
					}
				}

				result[fieldName] = subResult
			}
		case reflect.Slice:
			if fieldVal.Len() > 0 {
				slice := make([]any, fieldVal.Len())
				for j := 0; j < fieldVal.Len(); j++ {
					slice[j] = fieldVal.Index(j).Interface()
				}
				result[fieldName] = slice
			}
		default:
			result[fieldName] = fieldVal.Interface()
		}
	}

	return result
}
