// Code generated by kaitai-test-gen-simple.go; DO NOT EDIT.
package formats_test

import (
	"bytes"
	"context"
	"log/slog"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/twinfer/kbin-plugin/pkg/kaitaistruct"
	expr_str_ops_kaitai "github.com/twinfer/kbin-plugin/testdata/formats_kaitai_go_gen/expr_str_ops"
)

func TestParse_ExprStrOps(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "expr_str_ops.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)
	logger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug}))
	interpreter, err := kaitaistruct.NewKaitaiInterpreter(schema, logger)
	require.NoError(t, err)

	// Read binary file
	binPath := filepath.Join("../../../test/src", "term_strz.bin")
	binData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse with custom parser
	stream := kaitai.NewStream(bytes.NewReader(binData))
	parsed, err := interpreter.Parse(context.Background(), stream)
	require.NoError(t, err)

	// Convert to map for assertions
	customMap := kaitaistruct.ParsedDataToMap(parsed).(map[string]any)

	// Assertions from KSC test

	// Assert One
	if one_val, ok := customMap["One"]; ok {
		assert.EqualValues(t, "foo|b", one_val)
	} else {
		t.Fatalf("Field 'One' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert OneLen
	if onelen_val, ok := customMap["OneLen"]; ok {
		assert.EqualValues(t, 5, onelen_val)
	} else {
		t.Fatalf("Field 'OneLen' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert OneRev
	if onerev_val, ok := customMap["OneRev"]; ok {
		assert.EqualValues(t, "b|oof", onerev_val)
	} else {
		t.Fatalf("Field 'OneRev' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert OneSubstr0To3
	if onesubstr0to3_val, ok := customMap["OneSubstr0To3"]; ok {
		assert.EqualValues(t, "foo", onesubstr0to3_val)
	} else {
		t.Fatalf("Field 'OneSubstr0To3' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert OneSubstr2To5
	if onesubstr2to5_val, ok := customMap["OneSubstr2To5"]; ok {
		assert.EqualValues(t, "o|b", onesubstr2to5_val)
	} else {
		t.Fatalf("Field 'OneSubstr2To5' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert OneSubstr3To3
	if onesubstr3to3_val, ok := customMap["OneSubstr3To3"]; ok {
		assert.EqualValues(t, "", onesubstr3to3_val)
	} else {
		t.Fatalf("Field 'OneSubstr3To3' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert OneSubstr0To0
	if onesubstr0to0_val, ok := customMap["OneSubstr0To0"]; ok {
		assert.EqualValues(t, "", onesubstr0to0_val)
	} else {
		t.Fatalf("Field 'OneSubstr0To0' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Two
	if two_val, ok := customMap["Two"]; ok {
		assert.EqualValues(t, "0123456789", two_val)
	} else {
		t.Fatalf("Field 'Two' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert TwoLen
	if twolen_val, ok := customMap["TwoLen"]; ok {
		assert.EqualValues(t, 10, twolen_val)
	} else {
		t.Fatalf("Field 'TwoLen' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert TwoRev
	if tworev_val, ok := customMap["TwoRev"]; ok {
		assert.EqualValues(t, "9876543210", tworev_val)
	} else {
		t.Fatalf("Field 'TwoRev' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert TwoSubstr0To7
	if twosubstr0to7_val, ok := customMap["TwoSubstr0To7"]; ok {
		assert.EqualValues(t, "0123456", twosubstr0to7_val)
	} else {
		t.Fatalf("Field 'TwoSubstr0To7' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert TwoSubstr4To10
	if twosubstr4to10_val, ok := customMap["TwoSubstr4To10"]; ok {
		assert.EqualValues(t, "456789", twosubstr4to10_val)
	} else {
		t.Fatalf("Field 'TwoSubstr4To10' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert TwoSubstr0To10
	if twosubstr0to10_val, ok := customMap["TwoSubstr0To10"]; ok {
		assert.EqualValues(t, "0123456789", twosubstr0to10_val)
	} else {
		t.Fatalf("Field 'TwoSubstr0To10' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert ToIAttr
	if toiattr_val, ok := customMap["ToIAttr"]; ok {
		assert.EqualValues(t, 9173, toiattr_val)
	} else {
		t.Fatalf("Field 'ToIAttr' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert ToIR10
	if toir10_val, ok := customMap["ToIR10"]; ok {
		assert.EqualValues(t, -72, toir10_val)
	} else {
		t.Fatalf("Field 'ToIR10' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert ToIR2
	if toir2_val, ok := customMap["ToIR2"]; ok {
		assert.EqualValues(t, 86, toir2_val)
	} else {
		t.Fatalf("Field 'ToIR2' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert ToIR8
	if toir8_val, ok := customMap["ToIR8"]; ok {
		assert.EqualValues(t, 465, toir8_val)
	} else {
		t.Fatalf("Field 'ToIR8' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert ToIR16
	if toir16_val, ok := customMap["ToIR16"]; ok {
		assert.EqualValues(t, 18383, toir16_val)
	} else {
		t.Fatalf("Field 'ToIR16' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

}

func TestSerialize_ExprStrOps(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "expr_str_ops.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)

	serializer, err := kaitaistruct.NewKaitaiSerializer(schema, nil)
	require.NoError(t, err)

	// Read original binary
	binPath := filepath.Join("../../../test/src", "term_strz.bin")
	originalData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse original
	stream := kaitai.NewStream(bytes.NewReader(originalData))
	original := expr_str_ops_kaitai.NewExprStrOps()
	err = original.Read(stream, original, original)
	require.NoError(t, err)

	// Serialize and verify round-trip
	inputMap := structToMapExprStrOps(t, original)

	serialized, err := serializer.Serialize(context.Background(), inputMap)
	require.NoError(t, err)

	// Parse serialized data
	stream2 := kaitai.NewStream(bytes.NewReader(serialized))
	reparsed := expr_str_ops_kaitai.NewExprStrOps()
	err = reparsed.Read(stream2, reparsed, reparsed)
	require.NoError(t, err)

	// Compare structures with Phase 2/3 enhanced comparison
	cmpOpts := []cmp.Option{
		cmpopts.IgnoreUnexported(
			kaitai.Stream{},
		),
		cmpopts.IgnoreFields(expr_str_ops_kaitai.ExprStrOps{}, "_io", "_parent", "_root"),
		cmpopts.EquateEmpty(),
	}
	if diff := cmp.Diff(original, reparsed, cmpOpts...); diff != "" {
		t.Errorf("Serialization mismatch (-original +reparsed):\n%s", diff)
	}
}

// structToMapExprStrOps converts KSC struct to map for serializer
func structToMapExprStrOps(t *testing.T, data any) map[string]any {
	// Use reflection to handle KSC structs with method-based values
	return structToMapReflectiveExprStrOps(t, data)
}

// structToMapReflectiveExprStrOps uses reflection to convert KSC structs including method calls
func structToMapReflectiveExprStrOps(t *testing.T, data any) map[string]any {
	result := make(map[string]any)

	val := reflect.ValueOf(data)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	typ := val.Type()

	// Process fields
	for i := 0; i < val.NumField(); i++ {
		field := typ.Field(i)
		fieldVal := val.Field(i)

		// Skip internal KSC fields
		if strings.HasPrefix(field.Name, "_") {
			continue
		}

		fieldName := strings.ToLower(field.Name)

		if !fieldVal.IsValid() || fieldVal.IsZero() {
			continue
		}

		// Handle different field types
		switch fieldVal.Kind() {
		case reflect.Ptr:
			if !fieldVal.IsNil() {
				// For custom types, check for AsInt/AsStr methods
				subResult := make(map[string]any)

				// Try to call AsInt method
				if method := fieldVal.MethodByName("AsInt"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asint"] = results[0].Interface()
					}
				}

				// Try to call AsStr method
				if method := fieldVal.MethodByName("AsStr"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asstr"] = results[0].Interface()
					}
				}

				// Also include raw fields
				subMap := structToMapReflectiveExprStrOps(t, fieldVal.Interface())
				for k, v := range subMap {
					if _, exists := subResult[k]; !exists {
						subResult[k] = v
					}
				}

				result[fieldName] = subResult
			}
		case reflect.Slice:
			if fieldVal.Len() > 0 {
				slice := make([]any, fieldVal.Len())
				for j := 0; j < fieldVal.Len(); j++ {
					slice[j] = fieldVal.Index(j).Interface()
				}
				result[fieldName] = slice
			}
		default:
			result[fieldName] = fieldVal.Interface()
		}
	}

	return result
}
