// Code generated by kaitai-test-gen-simple.go; DO NOT EDIT.
package formats_test

import (
	"bytes"
	"context"
	"log/slog"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/twinfer/kbin-plugin/pkg/kaitaistruct"
	expr_bytes_cmp_kaitai "github.com/twinfer/kbin-plugin/testdata/formats_kaitai_go_gen/expr_bytes_cmp"
)

func TestParse_ExprBytesCmp(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "expr_bytes_cmp.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)
	logger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug}))
	interpreter, err := kaitaistruct.NewKaitaiInterpreter(schema, logger)
	require.NoError(t, err)

	// Read binary file
	binPath := filepath.Join("../../../test/src", "fixed_struct.bin")
	binData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse with custom parser
	stream := kaitai.NewStream(bytes.NewReader(binData))
	parsed, err := interpreter.Parse(context.Background(), stream)
	require.NoError(t, err)

	// Convert to map for assertions
	customMap := kaitaistruct.ParsedDataToMap(parsed).(map[string]any)

	// Assertions from KSC test

	// Assert One
	if one_val, ok := customMap["One"]; ok {
		assert.EqualValues(t, []uint8{80}, one_val)
	} else {
		t.Fatalf("Field 'One' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Two
	if two_val, ok := customMap["Two"]; ok {
		assert.EqualValues(t, []uint8{65, 67, 75}, two_val)
	} else {
		t.Fatalf("Field 'Two' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert IsEq
	if iseq_val, ok := customMap["IsEq"]; ok {
		assert.EqualValues(t, true, iseq_val)
	} else {
		t.Fatalf("Field 'IsEq' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert IsNe
	if isne_val, ok := customMap["IsNe"]; ok {
		assert.EqualValues(t, false, isne_val)
	} else {
		t.Fatalf("Field 'IsNe' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert IsLt
	if islt_val, ok := customMap["IsLt"]; ok {
		assert.EqualValues(t, true, islt_val)
	} else {
		t.Fatalf("Field 'IsLt' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert IsGt
	if isgt_val, ok := customMap["IsGt"]; ok {
		assert.EqualValues(t, false, isgt_val)
	} else {
		t.Fatalf("Field 'IsGt' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert IsLe
	if isle_val, ok := customMap["IsLe"]; ok {
		assert.EqualValues(t, true, isle_val)
	} else {
		t.Fatalf("Field 'IsLe' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert IsGe
	if isge_val, ok := customMap["IsGe"]; ok {
		assert.EqualValues(t, false, isge_val)
	} else {
		t.Fatalf("Field 'IsGe' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert IsLt2
	if islt2_val, ok := customMap["IsLt2"]; ok {
		assert.EqualValues(t, false, islt2_val)
	} else {
		t.Fatalf("Field 'IsLt2' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert IsGt2
	if isgt2_val, ok := customMap["IsGt2"]; ok {
		assert.EqualValues(t, true, isgt2_val)
	} else {
		t.Fatalf("Field 'IsGt2' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

}

func TestSerialize_ExprBytesCmp(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "expr_bytes_cmp.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)

	serializer, err := kaitaistruct.NewKaitaiSerializer(schema, nil)
	require.NoError(t, err)

	// Read original binary
	binPath := filepath.Join("../../../test/src", "fixed_struct.bin")
	originalData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse original
	stream := kaitai.NewStream(bytes.NewReader(originalData))
	original := expr_bytes_cmp_kaitai.NewExprBytesCmp()
	err = original.Read(stream, original, original)
	require.NoError(t, err)

	// Serialize and verify round-trip
	inputMap := structToMapExprBytesCmp(t, original)

	serialized, err := serializer.Serialize(context.Background(), inputMap)
	require.NoError(t, err)

	// Parse serialized data
	stream2 := kaitai.NewStream(bytes.NewReader(serialized))
	reparsed := expr_bytes_cmp_kaitai.NewExprBytesCmp()
	err = reparsed.Read(stream2, reparsed, reparsed)
	require.NoError(t, err)

	// Compare structures with Phase 2/3 enhanced comparison
	cmpOpts := []cmp.Option{
		cmpopts.IgnoreUnexported(
			kaitai.Stream{},
		),
		cmpopts.IgnoreFields(expr_bytes_cmp_kaitai.ExprBytesCmp{}, "_io", "_parent", "_root"),
		cmpopts.EquateEmpty(),
	}
	if diff := cmp.Diff(original, reparsed, cmpOpts...); diff != "" {
		t.Errorf("Serialization mismatch (-original +reparsed):\n%s", diff)
	}
}

// structToMapExprBytesCmp converts KSC struct to map for serializer
func structToMapExprBytesCmp(t *testing.T, data any) map[string]any {
	// Use reflection to handle KSC structs with method-based values
	return structToMapReflectiveExprBytesCmp(t, data)
}

// structToMapReflectiveExprBytesCmp uses reflection to convert KSC structs including method calls
func structToMapReflectiveExprBytesCmp(t *testing.T, data any) map[string]any {
	result := make(map[string]any)

	val := reflect.ValueOf(data)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	typ := val.Type()

	// Process fields
	for i := 0; i < val.NumField(); i++ {
		field := typ.Field(i)
		fieldVal := val.Field(i)

		// Skip internal KSC fields
		if strings.HasPrefix(field.Name, "_") {
			continue
		}

		fieldName := strings.ToLower(field.Name)

		if !fieldVal.IsValid() || fieldVal.IsZero() {
			continue
		}

		// Handle different field types
		switch fieldVal.Kind() {
		case reflect.Ptr:
			if !fieldVal.IsNil() {
				// For custom types, check for AsInt/AsStr methods
				subResult := make(map[string]any)

				// Try to call AsInt method
				if method := fieldVal.MethodByName("AsInt"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asint"] = results[0].Interface()
					}
				}

				// Try to call AsStr method
				if method := fieldVal.MethodByName("AsStr"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asstr"] = results[0].Interface()
					}
				}

				// Also include raw fields
				subMap := structToMapReflectiveExprBytesCmp(t, fieldVal.Interface())
				for k, v := range subMap {
					if _, exists := subResult[k]; !exists {
						subResult[k] = v
					}
				}

				result[fieldName] = subResult
			}
		case reflect.Slice:
			if fieldVal.Len() > 0 {
				slice := make([]any, fieldVal.Len())
				for j := 0; j < fieldVal.Len(); j++ {
					slice[j] = fieldVal.Index(j).Interface()
				}
				result[fieldName] = slice
			}
		default:
			result[fieldName] = fieldVal.Interface()
		}
	}

	return result
}
