// Code generated by kaitai-test-gen-simple.go; DO NOT EDIT.
package formats_test

import (
	"bytes"
	"context"
	"log/slog"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/twinfer/kbin-plugin/pkg/kaitaistruct"
	expr_array_kaitai "github.com/twinfer/kbin-plugin/testdata/formats_kaitai_go_gen/expr_array"
)

func TestParse_ExprArray(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "expr_array.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)
	logger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug}))
	interpreter, err := kaitaistruct.NewKaitaiInterpreter(schema, logger)
	require.NoError(t, err)

	// Read binary file
	binPath := filepath.Join("../../../test/src", "expr_array.bin")
	binData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse with custom parser
	stream := kaitai.NewStream(bytes.NewReader(binData))
	parsed, err := interpreter.Parse(context.Background(), stream)
	require.NoError(t, err)

	// Convert to map for assertions
	customMap := kaitaistruct.ParsedDataToMap(parsed).(map[string]any)

	// Assertions from KSC test

	// Assert AintSize
	if aintsize_val, ok := customMap["AintSize"]; ok {
		assert.EqualValues(t, 4, aintsize_val)
	} else {
		t.Fatalf("Field 'AintSize' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert AintFirst
	if aintfirst_val, ok := customMap["AintFirst"]; ok {
		assert.EqualValues(t, 7657765, aintfirst_val)
	} else {
		t.Fatalf("Field 'AintFirst' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert AintLast
	if aintlast_val, ok := customMap["AintLast"]; ok {
		assert.EqualValues(t, 16272640, aintlast_val)
	} else {
		t.Fatalf("Field 'AintLast' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert AintMin
	if aintmin_val, ok := customMap["AintMin"]; ok {
		assert.EqualValues(t, 49185, aintmin_val)
	} else {
		t.Fatalf("Field 'AintMin' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert AintMax
	if aintmax_val, ok := customMap["AintMax"]; ok {
		assert.EqualValues(t, 1123362332, aintmax_val)
	} else {
		t.Fatalf("Field 'AintMax' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert AfloatSize
	if afloatsize_val, ok := customMap["AfloatSize"]; ok {
		assert.EqualValues(t, 3, afloatsize_val)
	} else {
		t.Fatalf("Field 'AfloatSize' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert AstrSize
	if astrsize_val, ok := customMap["AstrSize"]; ok {
		assert.EqualValues(t, 3, astrsize_val)
	} else {
		t.Fatalf("Field 'AstrSize' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert AstrFirst
	if astrfirst_val, ok := customMap["AstrFirst"]; ok {
		assert.EqualValues(t, "foo", astrfirst_val)
	} else {
		t.Fatalf("Field 'AstrFirst' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert AstrLast
	if astrlast_val, ok := customMap["AstrLast"]; ok {
		assert.EqualValues(t, "baz", astrlast_val)
	} else {
		t.Fatalf("Field 'AstrLast' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert AstrMin
	if astrmin_val, ok := customMap["AstrMin"]; ok {
		assert.EqualValues(t, "bar", astrmin_val)
	} else {
		t.Fatalf("Field 'AstrMin' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert AstrMax
	if astrmax_val, ok := customMap["AstrMax"]; ok {
		assert.EqualValues(t, "foo", astrmax_val)
	} else {
		t.Fatalf("Field 'AstrMax' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

}

func TestSerialize_ExprArray(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "expr_array.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)

	serializer, err := kaitaistruct.NewKaitaiSerializer(schema, nil)
	require.NoError(t, err)

	// Read original binary
	binPath := filepath.Join("../../../test/src", "expr_array.bin")
	originalData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse original
	stream := kaitai.NewStream(bytes.NewReader(originalData))
	original := expr_array_kaitai.NewExprArray()
	err = original.Read(stream, original, original)
	require.NoError(t, err)

	// Serialize and verify round-trip
	inputMap := structToMapExprArray(t, original)

	serialized, err := serializer.Serialize(context.Background(), inputMap)
	require.NoError(t, err)

	// Parse serialized data
	stream2 := kaitai.NewStream(bytes.NewReader(serialized))
	reparsed := expr_array_kaitai.NewExprArray()
	err = reparsed.Read(stream2, reparsed, reparsed)
	require.NoError(t, err)

	// Compare structures with Phase 2/3 enhanced comparison
	cmpOpts := []cmp.Option{
		cmpopts.IgnoreUnexported(
			kaitai.Stream{},
		),
		cmpopts.IgnoreFields(expr_array_kaitai.ExprArray{}, "_io", "_parent", "_root"),
		cmpopts.EquateEmpty(),
	}
	if diff := cmp.Diff(original, reparsed, cmpOpts...); diff != "" {
		t.Errorf("Serialization mismatch (-original +reparsed):\n%s", diff)
	}
}

// structToMapExprArray converts KSC struct to map for serializer
func structToMapExprArray(t *testing.T, data any) map[string]any {
	// Use reflection to handle KSC structs with method-based values
	return structToMapReflectiveExprArray(t, data)
}

// structToMapReflectiveExprArray uses reflection to convert KSC structs including method calls
func structToMapReflectiveExprArray(t *testing.T, data any) map[string]any {
	result := make(map[string]any)

	val := reflect.ValueOf(data)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	typ := val.Type()

	// Process fields
	for i := 0; i < val.NumField(); i++ {
		field := typ.Field(i)
		fieldVal := val.Field(i)

		// Skip internal KSC fields
		if strings.HasPrefix(field.Name, "_") {
			continue
		}

		fieldName := strings.ToLower(field.Name)

		if !fieldVal.IsValid() || fieldVal.IsZero() {
			continue
		}

		// Handle different field types
		switch fieldVal.Kind() {
		case reflect.Ptr:
			if !fieldVal.IsNil() {
				// For custom types, check for AsInt/AsStr methods
				subResult := make(map[string]any)

				// Try to call AsInt method
				if method := fieldVal.MethodByName("AsInt"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asint"] = results[0].Interface()
					}
				}

				// Try to call AsStr method
				if method := fieldVal.MethodByName("AsStr"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asstr"] = results[0].Interface()
					}
				}

				// Also include raw fields
				subMap := structToMapReflectiveExprArray(t, fieldVal.Interface())
				for k, v := range subMap {
					if _, exists := subResult[k]; !exists {
						subResult[k] = v
					}
				}

				result[fieldName] = subResult
			}
		case reflect.Slice:
			if fieldVal.Len() > 0 {
				slice := make([]any, fieldVal.Len())
				for j := 0; j < fieldVal.Len(); j++ {
					slice[j] = fieldVal.Index(j).Interface()
				}
				result[fieldName] = slice
			}
		default:
			result[fieldName] = fieldVal.Interface()
		}
	}

	return result
}
