// Code generated by kaitai-test-gen-simple.go; DO NOT EDIT.
package formats_test

import (
	"bytes"
	"context"
	"io"
	"log/slog"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/twinfer/kbin-plugin/pkg/kaitaistruct"
	if_struct_kaitai "github.com/twinfer/kbin-plugin/testdata/formats_kaitai_go_gen/if_struct"
)

func TestParse_IfStruct(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "if_struct.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)
	logger := slog.New(slog.NewTextHandler(io.Discard, nil))
	interpreter, err := kaitaistruct.NewKaitaiInterpreter(schema, logger)
	require.NoError(t, err)

	// Read binary file
	binPath := filepath.Join("../../../test/src", "if_struct.bin")
	binData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse with custom parser
	stream := kaitai.NewStream(bytes.NewReader(binData))
	parsed, err := interpreter.Parse(context.Background(), stream)
	require.NoError(t, err)

	// Convert to map for assertions
	customMap := kaitaistruct.ParsedDataToMap(parsed).(map[string]any)

	// Assertions from KSC test

	// Assert Op1.Opcode
	if op1_opcode_lvl0_map, ok := customMap["op1"].(map[string]any); ok {
		if op1_opcode_val, ok := op1_opcode_lvl0_map["opcode"]; ok {
			assert.EqualValues(t, 83, op1_opcode_val)
		} else {
			t.Fatalf("Field 'opcode' not found in op1_opcode_lvl0_map (keys: %v)", maps.Keys(op1_opcode_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'op1' not found or not a map while asserting Op1.Opcode")
	}

	// Assert Op1.ArgStr.Str
	if op1_arg_str_str_lvl0_map, ok := customMap["op1"].(map[string]any); ok {
		if op1_arg_str_str_lvl1_map, ok := op1_arg_str_str_lvl0_map["arg_str"].(map[string]any); ok {
			if op1_arg_str_str_val, ok := op1_arg_str_str_lvl1_map["str"]; ok {
				assert.EqualValues(t, "foo", op1_arg_str_str_val)
			} else {
				t.Fatalf("Field 'str' not found in op1_arg_str_str_lvl1_map (keys: %v)", maps.Keys(op1_arg_str_str_lvl1_map))
			}
		} else {
			t.Fatalf("Field 'arg_str' not found or not a map while asserting Op1.ArgStr.Str")
		}
	} else {
		t.Fatalf("Field 'op1' not found or not a map while asserting Op1.ArgStr.Str")
	}

	// Assert Op2.Opcode
	if op2_opcode_lvl0_map, ok := customMap["op2"].(map[string]any); ok {
		if op2_opcode_val, ok := op2_opcode_lvl0_map["opcode"]; ok {
			assert.EqualValues(t, 84, op2_opcode_val)
		} else {
			t.Fatalf("Field 'opcode' not found in op2_opcode_lvl0_map (keys: %v)", maps.Keys(op2_opcode_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'op2' not found or not a map while asserting Op2.Opcode")
	}

	// Assert Op2.ArgTuple.Num1
	if op2_arg_tuple_num1_lvl0_map, ok := customMap["op2"].(map[string]any); ok {
		if op2_arg_tuple_num1_lvl1_map, ok := op2_arg_tuple_num1_lvl0_map["arg_tuple"].(map[string]any); ok {
			if op2_arg_tuple_num1_val, ok := op2_arg_tuple_num1_lvl1_map["num1"]; ok {
				assert.EqualValues(t, 66, op2_arg_tuple_num1_val)
			} else {
				t.Fatalf("Field 'num1' not found in op2_arg_tuple_num1_lvl1_map (keys: %v)", maps.Keys(op2_arg_tuple_num1_lvl1_map))
			}
		} else {
			t.Fatalf("Field 'arg_tuple' not found or not a map while asserting Op2.ArgTuple.Num1")
		}
	} else {
		t.Fatalf("Field 'op2' not found or not a map while asserting Op2.ArgTuple.Num1")
	}

	// Assert Op2.ArgTuple.Num2
	if op2_arg_tuple_num2_lvl0_map, ok := customMap["op2"].(map[string]any); ok {
		if op2_arg_tuple_num2_lvl1_map, ok := op2_arg_tuple_num2_lvl0_map["arg_tuple"].(map[string]any); ok {
			if op2_arg_tuple_num2_val, ok := op2_arg_tuple_num2_lvl1_map["num2"]; ok {
				assert.EqualValues(t, 67, op2_arg_tuple_num2_val)
			} else {
				t.Fatalf("Field 'num2' not found in op2_arg_tuple_num2_lvl1_map (keys: %v)", maps.Keys(op2_arg_tuple_num2_lvl1_map))
			}
		} else {
			t.Fatalf("Field 'arg_tuple' not found or not a map while asserting Op2.ArgTuple.Num2")
		}
	} else {
		t.Fatalf("Field 'op2' not found or not a map while asserting Op2.ArgTuple.Num2")
	}

	// Assert Op3.Opcode
	if op3_opcode_lvl0_map, ok := customMap["op3"].(map[string]any); ok {
		if op3_opcode_val, ok := op3_opcode_lvl0_map["opcode"]; ok {
			assert.EqualValues(t, 83, op3_opcode_val)
		} else {
			t.Fatalf("Field 'opcode' not found in op3_opcode_lvl0_map (keys: %v)", maps.Keys(op3_opcode_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'op3' not found or not a map while asserting Op3.Opcode")
	}

	// Assert Op3.ArgStr.Str
	if op3_arg_str_str_lvl0_map, ok := customMap["op3"].(map[string]any); ok {
		if op3_arg_str_str_lvl1_map, ok := op3_arg_str_str_lvl0_map["arg_str"].(map[string]any); ok {
			if op3_arg_str_str_val, ok := op3_arg_str_str_lvl1_map["str"]; ok {
				assert.EqualValues(t, "bar", op3_arg_str_str_val)
			} else {
				t.Fatalf("Field 'str' not found in op3_arg_str_str_lvl1_map (keys: %v)", maps.Keys(op3_arg_str_str_lvl1_map))
			}
		} else {
			t.Fatalf("Field 'arg_str' not found or not a map while asserting Op3.ArgStr.Str")
		}
	} else {
		t.Fatalf("Field 'op3' not found or not a map while asserting Op3.ArgStr.Str")
	}

}

func TestSerialize_IfStruct(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "if_struct.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)

	serializer, err := kaitaistruct.NewKaitaiSerializer(schema, nil)
	require.NoError(t, err)

	// Read original binary
	binPath := filepath.Join("../../../test/src", "if_struct.bin")
	originalData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse original
	stream := kaitai.NewStream(bytes.NewReader(originalData))
	original := if_struct_kaitai.NewIfStruct()
	err = original.Read(stream, original, original)
	require.NoError(t, err)

	// Serialize and verify round-trip
	inputMap := structToMapIfStruct(t, original)

	serialized, err := serializer.Serialize(context.Background(), inputMap)
	require.NoError(t, err)

	// Parse serialized data
	stream2 := kaitai.NewStream(bytes.NewReader(serialized))
	reparsed := if_struct_kaitai.NewIfStruct()
	err = reparsed.Read(stream2, reparsed, reparsed)
	require.NoError(t, err)

	// Compare structures with Phase 2/3 enhanced comparison
	cmpOpts := []cmp.Option{
		cmpopts.IgnoreUnexported(
			kaitai.Stream{},
		),
		cmpopts.IgnoreFields(if_struct_kaitai.IfStruct{}, "_io", "_parent", "_root"),
		cmpopts.EquateEmpty(),
	}
	if diff := cmp.Diff(original, reparsed, cmpOpts...); diff != "" {
		t.Errorf("Serialization mismatch (-original +reparsed):\n%s", diff)
	}
}

// structToMapIfStruct converts KSC struct to map for serializer
func structToMapIfStruct(t *testing.T, data any) map[string]any {
	// Use reflection to handle KSC structs with method-based values
	return structToMapReflectiveIfStruct(t, data)
}

// structToMapReflectiveIfStruct uses reflection to convert KSC structs including method calls
func structToMapReflectiveIfStruct(t *testing.T, data any) map[string]any {
	result := make(map[string]any)

	val := reflect.ValueOf(data)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	typ := val.Type()

	// Process fields
	for i := 0; i < val.NumField(); i++ {
		field := typ.Field(i)
		fieldVal := val.Field(i)

		// Skip internal KSC fields
		if strings.HasPrefix(field.Name, "_") {
			continue
		}

		fieldName := strings.ToLower(field.Name)

		if !fieldVal.IsValid() || fieldVal.IsZero() {
			continue
		}

		// Handle different field types
		switch fieldVal.Kind() {
		case reflect.Ptr:
			if !fieldVal.IsNil() {
				// For custom types, check for AsInt/AsStr methods
				subResult := make(map[string]any)

				// Try to call AsInt method
				if method := fieldVal.MethodByName("AsInt"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asint"] = results[0].Interface()
					}
				}

				// Try to call AsStr method
				if method := fieldVal.MethodByName("AsStr"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asstr"] = results[0].Interface()
					}
				}

				// Also include raw fields
				subMap := structToMapReflectiveIfStruct(t, fieldVal.Interface())
				for k, v := range subMap {
					if _, exists := subResult[k]; !exists {
						subResult[k] = v
					}
				}

				result[fieldName] = subResult
			}
		case reflect.Slice:
			if fieldVal.Len() > 0 {
				slice := make([]any, fieldVal.Len())
				for j := 0; j < fieldVal.Len(); j++ {
					slice[j] = fieldVal.Index(j).Interface()
				}
				result[fieldName] = slice
			}
		default:
			result[fieldName] = fieldVal.Interface()
		}
	}

	return result
}
