// Code generated by kaitai-test-gen-simple.go; DO NOT EDIT.
package formats_test

import (
	"bytes"
	"context"
	"log/slog"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/twinfer/kbin-plugin/pkg/kaitaistruct"
	imports_params_def_enum_imported_kaitai "github.com/twinfer/kbin-plugin/testdata/formats_kaitai_go_gen/imports_params_def_enum_imported"
)

func TestParse_ImportsParamsDefEnumImported(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "imports_params_def_enum_imported.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)
	logger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug}))
	interpreter, err := kaitaistruct.NewKaitaiInterpreter(schema, logger)
	require.NoError(t, err)

	// Read binary file
	binPath := filepath.Join("../../../test/src", "enum_0.bin")
	binData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse with custom parser
	stream := kaitai.NewStream(bytes.NewReader(binData))
	parsed, err := interpreter.Parse(context.Background(), stream)
	require.NoError(t, err)

	// Convert to map for assertions
	customMap := kaitaistruct.ParsedDataToMap(parsed).(map[string]any)

	// Assertions from KSC test

	// Assert One.Pet1
	if one_pet1_lvl0_map, ok := customMap["One"].(map[string]any); ok {
		if one_pet1_val, ok := one_pet1_lvl0_map["Pet1"]; ok {
			assert.EqualValues(t, Enum0_Animal__Cat, one_pet1_val)
		} else {
			t.Fatalf("Field 'Pet1' not found in one_pet1_lvl0_map (keys: %v)", maps.Keys(one_pet1_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'One' not found or not a map while asserting One.Pet1")
	}

	// Assert One.Pet2
	if one_pet2_lvl0_map, ok := customMap["One"].(map[string]any); ok {
		if one_pet2_val, ok := one_pet2_lvl0_map["Pet2"]; ok {
			assert.EqualValues(t, EnumDeep_Container1_Container2_Animal__Hare, one_pet2_val)
		} else {
			t.Fatalf("Field 'Pet2' not found in one_pet2_lvl0_map (keys: %v)", maps.Keys(one_pet2_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'One' not found or not a map while asserting One.Pet2")
	}

	// Assert Two.Pet1Param
	if two_pet1param_lvl0_map, ok := customMap["Two"].(map[string]any); ok {
		if two_pet1param_val, ok := two_pet1param_lvl0_map["Pet1Param"]; ok {
			assert.EqualValues(t, Enum0_Animal__Cat, two_pet1param_val)
		} else {
			t.Fatalf("Field 'Pet1Param' not found in two_pet1param_lvl0_map (keys: %v)", maps.Keys(two_pet1param_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'Two' not found or not a map while asserting Two.Pet1Param")
	}

	// Assert Two.Pet2Param
	if two_pet2param_lvl0_map, ok := customMap["Two"].(map[string]any); ok {
		if two_pet2param_val, ok := two_pet2param_lvl0_map["Pet2Param"]; ok {
			assert.EqualValues(t, EnumDeep_Container1_Container2_Animal__Hare, two_pet2param_val)
		} else {
			t.Fatalf("Field 'Pet2Param' not found in two_pet2param_lvl0_map (keys: %v)", maps.Keys(two_pet2param_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'Two' not found or not a map while asserting Two.Pet2Param")
	}

}

func TestSerialize_ImportsParamsDefEnumImported(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "imports_params_def_enum_imported.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)

	serializer, err := kaitaistruct.NewKaitaiSerializer(schema, nil)
	require.NoError(t, err)

	// Read original binary
	binPath := filepath.Join("../../../test/src", "enum_0.bin")
	originalData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse original
	stream := kaitai.NewStream(bytes.NewReader(originalData))
	original := imports_params_def_enum_imported_kaitai.NewImportsParamsDefEnumImported()
	err = original.Read(stream, original, original)
	require.NoError(t, err)

	// Serialize and verify round-trip
	inputMap := structToMapImportsParamsDefEnumImported(t, original)

	serialized, err := serializer.Serialize(context.Background(), inputMap)
	require.NoError(t, err)

	// Parse serialized data
	stream2 := kaitai.NewStream(bytes.NewReader(serialized))
	reparsed := imports_params_def_enum_imported_kaitai.NewImportsParamsDefEnumImported()
	err = reparsed.Read(stream2, reparsed, reparsed)
	require.NoError(t, err)

	// Compare structures with Phase 2/3 enhanced comparison
	cmpOpts := []cmp.Option{
		cmpopts.IgnoreUnexported(
			kaitai.Stream{},
		),
		cmpopts.IgnoreFields(imports_params_def_enum_imported_kaitai.ImportsParamsDefEnumImported{}, "_io", "_parent", "_root"),
		cmpopts.EquateEmpty(),
	}
	if diff := cmp.Diff(original, reparsed, cmpOpts...); diff != "" {
		t.Errorf("Serialization mismatch (-original +reparsed):\n%s", diff)
	}
}

// structToMapImportsParamsDefEnumImported converts KSC struct to map for serializer
func structToMapImportsParamsDefEnumImported(t *testing.T, data any) map[string]any {
	// Use reflection to handle KSC structs with method-based values
	return structToMapReflectiveImportsParamsDefEnumImported(t, data)
}

// structToMapReflectiveImportsParamsDefEnumImported uses reflection to convert KSC structs including method calls
func structToMapReflectiveImportsParamsDefEnumImported(t *testing.T, data any) map[string]any {
	result := make(map[string]any)

	val := reflect.ValueOf(data)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	typ := val.Type()

	// Process fields
	for i := 0; i < val.NumField(); i++ {
		field := typ.Field(i)
		fieldVal := val.Field(i)

		// Skip internal KSC fields
		if strings.HasPrefix(field.Name, "_") {
			continue
		}

		fieldName := strings.ToLower(field.Name)

		if !fieldVal.IsValid() || fieldVal.IsZero() {
			continue
		}

		// Handle different field types
		switch fieldVal.Kind() {
		case reflect.Ptr:
			if !fieldVal.IsNil() {
				// For custom types, check for AsInt/AsStr methods
				subResult := make(map[string]any)

				// Try to call AsInt method
				if method := fieldVal.MethodByName("AsInt"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asint"] = results[0].Interface()
					}
				}

				// Try to call AsStr method
				if method := fieldVal.MethodByName("AsStr"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asstr"] = results[0].Interface()
					}
				}

				// Also include raw fields
				subMap := structToMapReflectiveImportsParamsDefEnumImported(t, fieldVal.Interface())
				for k, v := range subMap {
					if _, exists := subResult[k]; !exists {
						subResult[k] = v
					}
				}

				result[fieldName] = subResult
			}
		case reflect.Slice:
			if fieldVal.Len() > 0 {
				slice := make([]any, fieldVal.Len())
				for j := 0; j < fieldVal.Len(); j++ {
					slice[j] = fieldVal.Index(j).Interface()
				}
				result[fieldName] = slice
			}
		default:
			result[fieldName] = fieldVal.Interface()
		}
	}

	return result
}
