// Code generated by kaitai-test-gen-simple.go; DO NOT EDIT.
package formats_test

import (
	"bytes"
	"context"
	"log/slog"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/twinfer/kbin-plugin/pkg/kaitaistruct"
	integers_kaitai "github.com/twinfer/kbin-plugin/testdata/formats_kaitai_go_gen/integers"
)

func TestParse_Integers(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "integers.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)
	logger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug}))
	interpreter, err := kaitaistruct.NewKaitaiInterpreter(schema, logger)
	require.NoError(t, err)

	// Read binary file
	binPath := filepath.Join("../../../test/src", "fixed_struct.bin")
	binData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse with custom parser
	stream := kaitai.NewStream(bytes.NewReader(binData))
	parsed, err := interpreter.Parse(context.Background(), stream)
	require.NoError(t, err)

	// Convert to map for assertions
	customMap := kaitaistruct.ParsedDataToMap(parsed).(map[string]any)

	// Assertions from KSC test

	// Assert Uint8
	if uint8_val, ok := customMap["Uint8"]; ok {
		assert.EqualValues(t, 255, uint8_val)
	} else {
		t.Fatalf("Field 'Uint8' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Uint16
	if uint16_val, ok := customMap["Uint16"]; ok {
		assert.EqualValues(t, 65535, uint16_val)
	} else {
		t.Fatalf("Field 'Uint16' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Uint32
	if uint32_val, ok := customMap["Uint32"]; ok {
		assert.EqualValues(t, uint32(4294967295), uint32_val)
	} else {
		t.Fatalf("Field 'Uint32' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Uint64
	if uint64_val, ok := customMap["Uint64"]; ok {
		assert.EqualValues(t, uint64(18446744073709551615), uint64_val)
	} else {
		t.Fatalf("Field 'Uint64' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Sint8
	if sint8_val, ok := customMap["Sint8"]; ok {
		assert.EqualValues(t, -1, sint8_val)
	} else {
		t.Fatalf("Field 'Sint8' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Sint16
	if sint16_val, ok := customMap["Sint16"]; ok {
		assert.EqualValues(t, -1, sint16_val)
	} else {
		t.Fatalf("Field 'Sint16' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Sint32
	if sint32_val, ok := customMap["Sint32"]; ok {
		assert.EqualValues(t, -1, sint32_val)
	} else {
		t.Fatalf("Field 'Sint32' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Sint64
	if sint64_val, ok := customMap["Sint64"]; ok {
		assert.EqualValues(t, -1, sint64_val)
	} else {
		t.Fatalf("Field 'Sint64' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Uint16le
	if uint16le_val, ok := customMap["Uint16le"]; ok {
		assert.EqualValues(t, 66, uint16le_val)
	} else {
		t.Fatalf("Field 'Uint16le' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Uint32le
	if uint32le_val, ok := customMap["Uint32le"]; ok {
		assert.EqualValues(t, 66, uint32le_val)
	} else {
		t.Fatalf("Field 'Uint32le' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Uint64le
	if uint64le_val, ok := customMap["Uint64le"]; ok {
		assert.EqualValues(t, 66, uint64le_val)
	} else {
		t.Fatalf("Field 'Uint64le' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Sint16le
	if sint16le_val, ok := customMap["Sint16le"]; ok {
		assert.EqualValues(t, -66, sint16le_val)
	} else {
		t.Fatalf("Field 'Sint16le' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Sint32le
	if sint32le_val, ok := customMap["Sint32le"]; ok {
		assert.EqualValues(t, -66, sint32le_val)
	} else {
		t.Fatalf("Field 'Sint32le' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Sint64le
	if sint64le_val, ok := customMap["Sint64le"]; ok {
		assert.EqualValues(t, -66, sint64le_val)
	} else {
		t.Fatalf("Field 'Sint64le' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Uint16be
	if uint16be_val, ok := customMap["Uint16be"]; ok {
		assert.EqualValues(t, 66, uint16be_val)
	} else {
		t.Fatalf("Field 'Uint16be' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Uint32be
	if uint32be_val, ok := customMap["Uint32be"]; ok {
		assert.EqualValues(t, 66, uint32be_val)
	} else {
		t.Fatalf("Field 'Uint32be' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Uint64be
	if uint64be_val, ok := customMap["Uint64be"]; ok {
		assert.EqualValues(t, 66, uint64be_val)
	} else {
		t.Fatalf("Field 'Uint64be' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Sint16be
	if sint16be_val, ok := customMap["Sint16be"]; ok {
		assert.EqualValues(t, -66, sint16be_val)
	} else {
		t.Fatalf("Field 'Sint16be' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Sint32be
	if sint32be_val, ok := customMap["Sint32be"]; ok {
		assert.EqualValues(t, -66, sint32be_val)
	} else {
		t.Fatalf("Field 'Sint32be' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert Sint64be
	if sint64be_val, ok := customMap["Sint64be"]; ok {
		assert.EqualValues(t, -66, sint64be_val)
	} else {
		t.Fatalf("Field 'Sint64be' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

}

func TestSerialize_Integers(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "integers.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)

	serializer, err := kaitaistruct.NewKaitaiSerializer(schema, nil)
	require.NoError(t, err)

	// Read original binary
	binPath := filepath.Join("../../../test/src", "fixed_struct.bin")
	originalData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse original
	stream := kaitai.NewStream(bytes.NewReader(originalData))
	original := integers_kaitai.NewIntegers()
	err = original.Read(stream, original, original)
	require.NoError(t, err)

	// Serialize and verify round-trip
	inputMap := structToMapIntegers(t, original)

	serialized, err := serializer.Serialize(context.Background(), inputMap)
	require.NoError(t, err)

	// Parse serialized data
	stream2 := kaitai.NewStream(bytes.NewReader(serialized))
	reparsed := integers_kaitai.NewIntegers()
	err = reparsed.Read(stream2, reparsed, reparsed)
	require.NoError(t, err)

	// Compare structures with Phase 2/3 enhanced comparison
	cmpOpts := []cmp.Option{
		cmpopts.IgnoreUnexported(
			kaitai.Stream{},
		),
		cmpopts.IgnoreFields(integers_kaitai.Integers{}, "_io", "_parent", "_root"),
		cmpopts.EquateEmpty(),
	}
	if diff := cmp.Diff(original, reparsed, cmpOpts...); diff != "" {
		t.Errorf("Serialization mismatch (-original +reparsed):\n%s", diff)
	}
}

// structToMapIntegers converts KSC struct to map for serializer
func structToMapIntegers(t *testing.T, data any) map[string]any {
	// Use reflection to handle KSC structs with method-based values
	return structToMapReflectiveIntegers(t, data)
}

// structToMapReflectiveIntegers uses reflection to convert KSC structs including method calls
func structToMapReflectiveIntegers(t *testing.T, data any) map[string]any {
	result := make(map[string]any)

	val := reflect.ValueOf(data)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	typ := val.Type()

	// Process fields
	for i := 0; i < val.NumField(); i++ {
		field := typ.Field(i)
		fieldVal := val.Field(i)

		// Skip internal KSC fields
		if strings.HasPrefix(field.Name, "_") {
			continue
		}

		fieldName := strings.ToLower(field.Name)

		if !fieldVal.IsValid() || fieldVal.IsZero() {
			continue
		}

		// Handle different field types
		switch fieldVal.Kind() {
		case reflect.Ptr:
			if !fieldVal.IsNil() {
				// For custom types, check for AsInt/AsStr methods
				subResult := make(map[string]any)

				// Try to call AsInt method
				if method := fieldVal.MethodByName("AsInt"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asint"] = results[0].Interface()
					}
				}

				// Try to call AsStr method
				if method := fieldVal.MethodByName("AsStr"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asstr"] = results[0].Interface()
					}
				}

				// Also include raw fields
				subMap := structToMapReflectiveIntegers(t, fieldVal.Interface())
				for k, v := range subMap {
					if _, exists := subResult[k]; !exists {
						subResult[k] = v
					}
				}

				result[fieldName] = subResult
			}
		case reflect.Slice:
			if fieldVal.Len() > 0 {
				slice := make([]any, fieldVal.Len())
				for j := 0; j < fieldVal.Len(); j++ {
					slice[j] = fieldVal.Index(j).Interface()
				}
				result[fieldName] = slice
			}
		default:
			result[fieldName] = fieldVal.Interface()
		}
	}

	return result
}
