// Code generated by kaitai-test-gen-simple.go; DO NOT EDIT.
package formats_test

import (
	"bytes"
	"context"
	"log/slog"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/twinfer/kbin-plugin/pkg/kaitaistruct"
	multiple_use_kaitai "github.com/twinfer/kbin-plugin/testdata/formats_kaitai_go_gen/multiple_use"
)

func TestParse_MultipleUse(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "multiple_use.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)
	logger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug}))
	interpreter, err := kaitaistruct.NewKaitaiInterpreter(schema, logger)
	require.NoError(t, err)

	// Read binary file
	binPath := filepath.Join("../../../test/src", "position_abs.bin")
	binData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse with custom parser
	stream := kaitai.NewStream(bytes.NewReader(binData))
	parsed, err := interpreter.Parse(context.Background(), stream)
	require.NoError(t, err)

	// Convert to map for assertions
	customMap := kaitaistruct.ParsedDataToMap(parsed).(map[string]any)

	// Assertions from KSC test

	// Assert T1.FirstUse.Value
	if t1_firstuse_value_lvl0_map, ok := customMap["T1"].(map[string]any); ok {
		if t1_firstuse_value_lvl1_map, ok := t1_firstuse_value_lvl0_map["FirstUse"].(map[string]any); ok {
			if t1_firstuse_value_val, ok := t1_firstuse_value_lvl1_map["Value"]; ok {
				assert.EqualValues(t, 32, t1_firstuse_value_val)
			} else {
				t.Fatalf("Field 'Value' not found in t1_firstuse_value_lvl1_map (keys: %v)", maps.Keys(t1_firstuse_value_lvl1_map))
			}
		} else {
			t.Fatalf("Field 'FirstUse' not found or not a map while asserting T1.FirstUse.Value")
		}
	} else {
		t.Fatalf("Field 'T1' not found or not a map while asserting T1.FirstUse.Value")
	}

	// Assert Tmp1.Value
	if tmp1_value_lvl0_map, ok := customMap["Tmp1"].(map[string]any); ok {
		if tmp1_value_val, ok := tmp1_value_lvl0_map["Value"]; ok {
			assert.EqualValues(t, 32, tmp1_value_val)
		} else {
			t.Fatalf("Field 'Value' not found in tmp1_value_lvl0_map (keys: %v)", maps.Keys(tmp1_value_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'Tmp1' not found or not a map while asserting Tmp1.Value")
	}

}

func TestSerialize_MultipleUse(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "multiple_use.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)

	serializer, err := kaitaistruct.NewKaitaiSerializer(schema, nil)
	require.NoError(t, err)

	// Read original binary
	binPath := filepath.Join("../../../test/src", "position_abs.bin")
	originalData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse original
	stream := kaitai.NewStream(bytes.NewReader(originalData))
	original := multiple_use_kaitai.NewMultipleUse()
	err = original.Read(stream, original, original)
	require.NoError(t, err)

	// Serialize and verify round-trip
	inputMap := structToMapMultipleUse(t, original)

	serialized, err := serializer.Serialize(context.Background(), inputMap)
	require.NoError(t, err)

	// Parse serialized data
	stream2 := kaitai.NewStream(bytes.NewReader(serialized))
	reparsed := multiple_use_kaitai.NewMultipleUse()
	err = reparsed.Read(stream2, reparsed, reparsed)
	require.NoError(t, err)

	// Compare structures with Phase 2/3 enhanced comparison
	cmpOpts := []cmp.Option{
		cmpopts.IgnoreUnexported(
			kaitai.Stream{},
		),
		cmpopts.IgnoreFields(multiple_use_kaitai.MultipleUse{}, "_io", "_parent", "_root"),
		cmpopts.EquateEmpty(),
	}
	if diff := cmp.Diff(original, reparsed, cmpOpts...); diff != "" {
		t.Errorf("Serialization mismatch (-original +reparsed):\n%s", diff)
	}
}

// structToMapMultipleUse converts KSC struct to map for serializer
func structToMapMultipleUse(t *testing.T, data any) map[string]any {
	// Use reflection to handle KSC structs with method-based values
	return structToMapReflectiveMultipleUse(t, data)
}

// structToMapReflectiveMultipleUse uses reflection to convert KSC structs including method calls
func structToMapReflectiveMultipleUse(t *testing.T, data any) map[string]any {
	result := make(map[string]any)

	val := reflect.ValueOf(data)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	typ := val.Type()

	// Process fields
	for i := 0; i < val.NumField(); i++ {
		field := typ.Field(i)
		fieldVal := val.Field(i)

		// Skip internal KSC fields
		if strings.HasPrefix(field.Name, "_") {
			continue
		}

		fieldName := strings.ToLower(field.Name)

		if !fieldVal.IsValid() || fieldVal.IsZero() {
			continue
		}

		// Handle different field types
		switch fieldVal.Kind() {
		case reflect.Ptr:
			if !fieldVal.IsNil() {
				// For custom types, check for AsInt/AsStr methods
				subResult := make(map[string]any)

				// Try to call AsInt method
				if method := fieldVal.MethodByName("AsInt"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asint"] = results[0].Interface()
					}
				}

				// Try to call AsStr method
				if method := fieldVal.MethodByName("AsStr"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asstr"] = results[0].Interface()
					}
				}

				// Also include raw fields
				subMap := structToMapReflectiveMultipleUse(t, fieldVal.Interface())
				for k, v := range subMap {
					if _, exists := subResult[k]; !exists {
						subResult[k] = v
					}
				}

				result[fieldName] = subResult
			}
		case reflect.Slice:
			if fieldVal.Len() > 0 {
				slice := make([]any, fieldVal.Len())
				for j := 0; j < fieldVal.Len(); j++ {
					slice[j] = fieldVal.Index(j).Interface()
				}
				result[fieldName] = slice
			}
		default:
			result[fieldName] = fieldVal.Interface()
		}
	}

	return result
}
