// Code generated by kaitai-test-gen-simple.go; DO NOT EDIT.
package formats_test

import (
	"bytes"
	"context"
	"log/slog"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/twinfer/kbin-plugin/pkg/kaitaistruct"
	nav_parent_false_kaitai "github.com/twinfer/kbin-plugin/testdata/formats_kaitai_go_gen/nav_parent_false"
)

func TestParse_NavParentFalse(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "nav_parent_false.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)
	logger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug}))
	interpreter, err := kaitaistruct.NewKaitaiInterpreter(schema, logger)
	require.NoError(t, err)

	// Read binary file
	binPath := filepath.Join("../../../test/src", "nav_parent_codes.bin")
	binData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse with custom parser
	stream := kaitai.NewStream(bytes.NewReader(binData))
	parsed, err := interpreter.Parse(context.Background(), stream)
	require.NoError(t, err)

	// Convert to map for assertions
	customMap := kaitaistruct.ParsedDataToMap(parsed).(map[string]any)

	// Assertions from KSC test

	// Assert ChildSize
	if childsize_val, ok := customMap["ChildSize"]; ok {
		assert.EqualValues(t, 3, childsize_val)
	} else {
		t.Fatalf("Field 'ChildSize' not found in customMap (keys: %v)", maps.Keys(customMap))
	}

	// Assert ElementA.Foo.Code
	if elementa_foo_code_lvl0_map, ok := customMap["ElementA"].(map[string]any); ok {
		if elementa_foo_code_lvl1_map, ok := elementa_foo_code_lvl0_map["Foo"].(map[string]any); ok {
			if elementa_foo_code_val, ok := elementa_foo_code_lvl1_map["Code"]; ok {
				assert.EqualValues(t, 73, elementa_foo_code_val)
			} else {
				t.Fatalf("Field 'Code' not found in elementa_foo_code_lvl1_map (keys: %v)", maps.Keys(elementa_foo_code_lvl1_map))
			}
		} else {
			t.Fatalf("Field 'Foo' not found or not a map while asserting ElementA.Foo.Code")
		}
	} else {
		t.Fatalf("Field 'ElementA' not found or not a map while asserting ElementA.Foo.Code")
	}

	// Assert ElementA.Foo.More
	if elementa_foo_more_lvl0_map, ok := customMap["ElementA"].(map[string]any); ok {
		if elementa_foo_more_lvl1_map, ok := elementa_foo_more_lvl0_map["Foo"].(map[string]any); ok {
			if elementa_foo_more_val, ok := elementa_foo_more_lvl1_map["More"]; ok {
				assert.EqualValues(t, []uint8{49, 50, 51}, elementa_foo_more_val)
			} else {
				t.Fatalf("Field 'More' not found in elementa_foo_more_lvl1_map (keys: %v)", maps.Keys(elementa_foo_more_lvl1_map))
			}
		} else {
			t.Fatalf("Field 'Foo' not found or not a map while asserting ElementA.Foo.More")
		}
	} else {
		t.Fatalf("Field 'ElementA' not found or not a map while asserting ElementA.Foo.More")
	}

	// Assert ElementA.Bar.Foo.Code
	if elementa_bar_foo_code_lvl0_map, ok := customMap["ElementA"].(map[string]any); ok {
		if elementa_bar_foo_code_lvl1_map, ok := elementa_bar_foo_code_lvl0_map["Bar"].(map[string]any); ok {
			if elementa_bar_foo_code_lvl2_map, ok := elementa_bar_foo_code_lvl1_map["Foo"].(map[string]any); ok {
				if elementa_bar_foo_code_val, ok := elementa_bar_foo_code_lvl2_map["Code"]; ok {
					assert.EqualValues(t, 66, elementa_bar_foo_code_val)
				} else {
					t.Fatalf("Field 'Code' not found in elementa_bar_foo_code_lvl2_map (keys: %v)", maps.Keys(elementa_bar_foo_code_lvl2_map))
				}
			} else {
				t.Fatalf("Field 'Foo' not found or not a map while asserting ElementA.Bar.Foo.Code")
			}
		} else {
			t.Fatalf("Field 'Bar' not found or not a map while asserting ElementA.Bar.Foo.Code")
		}
	} else {
		t.Fatalf("Field 'ElementA' not found or not a map while asserting ElementA.Bar.Foo.Code")
	}

	// Assert ElementB.Foo.Code
	if elementb_foo_code_lvl0_map, ok := customMap["ElementB"].(map[string]any); ok {
		if elementb_foo_code_lvl1_map, ok := elementb_foo_code_lvl0_map["Foo"].(map[string]any); ok {
			if elementb_foo_code_val, ok := elementb_foo_code_lvl1_map["Code"]; ok {
				assert.EqualValues(t, 98, elementb_foo_code_val)
			} else {
				t.Fatalf("Field 'Code' not found in elementb_foo_code_lvl1_map (keys: %v)", maps.Keys(elementb_foo_code_lvl1_map))
			}
		} else {
			t.Fatalf("Field 'Foo' not found or not a map while asserting ElementB.Foo.Code")
		}
	} else {
		t.Fatalf("Field 'ElementB' not found or not a map while asserting ElementB.Foo.Code")
	}

}

func TestSerialize_NavParentFalse(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "nav_parent_false.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)

	serializer, err := kaitaistruct.NewKaitaiSerializer(schema, nil)
	require.NoError(t, err)

	// Read original binary
	binPath := filepath.Join("../../../test/src", "nav_parent_codes.bin")
	originalData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse original
	stream := kaitai.NewStream(bytes.NewReader(originalData))
	original := nav_parent_false_kaitai.NewNavParentFalse()
	err = original.Read(stream, original, original)
	require.NoError(t, err)

	// Serialize and verify round-trip
	inputMap := structToMapNavParentFalse(t, original)

	serialized, err := serializer.Serialize(context.Background(), inputMap)
	require.NoError(t, err)

	// Parse serialized data
	stream2 := kaitai.NewStream(bytes.NewReader(serialized))
	reparsed := nav_parent_false_kaitai.NewNavParentFalse()
	err = reparsed.Read(stream2, reparsed, reparsed)
	require.NoError(t, err)

	// Compare structures with Phase 2/3 enhanced comparison
	cmpOpts := []cmp.Option{
		cmpopts.IgnoreUnexported(
			kaitai.Stream{},
		),
		cmpopts.IgnoreFields(nav_parent_false_kaitai.NavParentFalse{}, "_io", "_parent", "_root"),
		cmpopts.EquateEmpty(),
	}
	if diff := cmp.Diff(original, reparsed, cmpOpts...); diff != "" {
		t.Errorf("Serialization mismatch (-original +reparsed):\n%s", diff)
	}
}

// structToMapNavParentFalse converts KSC struct to map for serializer
func structToMapNavParentFalse(t *testing.T, data any) map[string]any {
	// Use reflection to handle KSC structs with method-based values
	return structToMapReflectiveNavParentFalse(t, data)
}

// structToMapReflectiveNavParentFalse uses reflection to convert KSC structs including method calls
func structToMapReflectiveNavParentFalse(t *testing.T, data any) map[string]any {
	result := make(map[string]any)

	val := reflect.ValueOf(data)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	typ := val.Type()

	// Process fields
	for i := 0; i < val.NumField(); i++ {
		field := typ.Field(i)
		fieldVal := val.Field(i)

		// Skip internal KSC fields
		if strings.HasPrefix(field.Name, "_") {
			continue
		}

		fieldName := strings.ToLower(field.Name)

		if !fieldVal.IsValid() || fieldVal.IsZero() {
			continue
		}

		// Handle different field types
		switch fieldVal.Kind() {
		case reflect.Ptr:
			if !fieldVal.IsNil() {
				// For custom types, check for AsInt/AsStr methods
				subResult := make(map[string]any)

				// Try to call AsInt method
				if method := fieldVal.MethodByName("AsInt"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asint"] = results[0].Interface()
					}
				}

				// Try to call AsStr method
				if method := fieldVal.MethodByName("AsStr"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asstr"] = results[0].Interface()
					}
				}

				// Also include raw fields
				subMap := structToMapReflectiveNavParentFalse(t, fieldVal.Interface())
				for k, v := range subMap {
					if _, exists := subResult[k]; !exists {
						subResult[k] = v
					}
				}

				result[fieldName] = subResult
			}
		case reflect.Slice:
			if fieldVal.Len() > 0 {
				slice := make([]any, fieldVal.Len())
				for j := 0; j < fieldVal.Len(); j++ {
					slice[j] = fieldVal.Index(j).Interface()
				}
				result[fieldName] = slice
			}
		default:
			result[fieldName] = fieldVal.Interface()
		}
	}

	return result
}
