// Code generated by kaitai-test-gen-simple.go; DO NOT EDIT.
package formats_test

import (
	"bytes"
	"context"
	"io"
	"log/slog"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/twinfer/kbin-plugin/pkg/kaitaistruct"
	nested_types2_kaitai "github.com/twinfer/kbin-plugin/testdata/formats_kaitai_go_gen/nested_types2"
)

func TestParse_NestedTypes2(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "nested_types2.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)
	logger := slog.New(slog.NewTextHandler(io.Discard, nil))
	interpreter, err := kaitaistruct.NewKaitaiInterpreter(schema, logger)
	require.NoError(t, err)

	// Read binary file
	binPath := filepath.Join("../../../test/src", "fixed_struct.bin")
	binData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse with custom parser
	stream := kaitai.NewStream(bytes.NewReader(binData))
	parsed, err := interpreter.Parse(context.Background(), stream)
	require.NoError(t, err)

	// Convert to map for assertions
	customMap := kaitaistruct.ParsedDataToMap(parsed).(map[string]any)

	// Assertions from KSC test

	// Assert One.TypedAtRoot.ValueB
	if one_typed_at_root_value_b_lvl0_map, ok := customMap["one"].(map[string]any); ok {
		if one_typed_at_root_value_b_lvl1_map, ok := one_typed_at_root_value_b_lvl0_map["typed_at_root"].(map[string]any); ok {
			if one_typed_at_root_value_b_val, ok := one_typed_at_root_value_b_lvl1_map["value_b"]; ok {
				assert.EqualValues(t, 80, one_typed_at_root_value_b_val)
			} else {
				t.Fatalf("Field 'value_b' not found in one_typed_at_root_value_b_lvl1_map (keys: %v)", maps.Keys(one_typed_at_root_value_b_lvl1_map))
			}
		} else {
			t.Fatalf("Field 'typed_at_root' not found or not a map while asserting One.TypedAtRoot.ValueB")
		}
	} else {
		t.Fatalf("Field 'one' not found or not a map while asserting One.TypedAtRoot.ValueB")
	}

	// Assert One.TypedHere1.ValueC
	if one_typed_here1_value_c_lvl0_map, ok := customMap["one"].(map[string]any); ok {
		if one_typed_here1_value_c_lvl1_map, ok := one_typed_here1_value_c_lvl0_map["typed_here1"].(map[string]any); ok {
			if one_typed_here1_value_c_val, ok := one_typed_here1_value_c_lvl1_map["value_c"]; ok {
				assert.EqualValues(t, 65, one_typed_here1_value_c_val)
			} else {
				t.Fatalf("Field 'value_c' not found in one_typed_here1_value_c_lvl1_map (keys: %v)", maps.Keys(one_typed_here1_value_c_lvl1_map))
			}
		} else {
			t.Fatalf("Field 'typed_here1' not found or not a map while asserting One.TypedHere1.ValueC")
		}
	} else {
		t.Fatalf("Field 'one' not found or not a map while asserting One.TypedHere1.ValueC")
	}

	// Assert One.TypedHere1.TypedHere.ValueD
	if one_typed_here1_typed_here_value_d_lvl0_map, ok := customMap["one"].(map[string]any); ok {
		if one_typed_here1_typed_here_value_d_lvl1_map, ok := one_typed_here1_typed_here_value_d_lvl0_map["typed_here1"].(map[string]any); ok {
			if one_typed_here1_typed_here_value_d_lvl2_map, ok := one_typed_here1_typed_here_value_d_lvl1_map["typed_here"].(map[string]any); ok {
				if one_typed_here1_typed_here_value_d_val, ok := one_typed_here1_typed_here_value_d_lvl2_map["value_d"]; ok {
					assert.EqualValues(t, 67, one_typed_here1_typed_here_value_d_val)
				} else {
					t.Fatalf("Field 'value_d' not found in one_typed_here1_typed_here_value_d_lvl2_map (keys: %v)", maps.Keys(one_typed_here1_typed_here_value_d_lvl2_map))
				}
			} else {
				t.Fatalf("Field 'typed_here' not found or not a map while asserting One.TypedHere1.TypedHere.ValueD")
			}
		} else {
			t.Fatalf("Field 'typed_here1' not found or not a map while asserting One.TypedHere1.TypedHere.ValueD")
		}
	} else {
		t.Fatalf("Field 'one' not found or not a map while asserting One.TypedHere1.TypedHere.ValueD")
	}

	// Assert One.TypedHere1.TypedParent.ValueCc
	if one_typed_here1_typed_parent_value_cc_lvl0_map, ok := customMap["one"].(map[string]any); ok {
		if one_typed_here1_typed_parent_value_cc_lvl1_map, ok := one_typed_here1_typed_parent_value_cc_lvl0_map["typed_here1"].(map[string]any); ok {
			if one_typed_here1_typed_parent_value_cc_lvl2_map, ok := one_typed_here1_typed_parent_value_cc_lvl1_map["typed_parent"].(map[string]any); ok {
				if one_typed_here1_typed_parent_value_cc_val, ok := one_typed_here1_typed_parent_value_cc_lvl2_map["value_cc"]; ok {
					assert.EqualValues(t, 75, one_typed_here1_typed_parent_value_cc_val)
				} else {
					t.Fatalf("Field 'value_cc' not found in one_typed_here1_typed_parent_value_cc_lvl2_map (keys: %v)", maps.Keys(one_typed_here1_typed_parent_value_cc_lvl2_map))
				}
			} else {
				t.Fatalf("Field 'typed_parent' not found or not a map while asserting One.TypedHere1.TypedParent.ValueCc")
			}
		} else {
			t.Fatalf("Field 'typed_here1' not found or not a map while asserting One.TypedHere1.TypedParent.ValueCc")
		}
	} else {
		t.Fatalf("Field 'one' not found or not a map while asserting One.TypedHere1.TypedParent.ValueCc")
	}

	// Assert One.TypedHere1.TypedRoot.ValueB
	if one_typed_here1_typed_root_value_b_lvl0_map, ok := customMap["one"].(map[string]any); ok {
		if one_typed_here1_typed_root_value_b_lvl1_map, ok := one_typed_here1_typed_root_value_b_lvl0_map["typed_here1"].(map[string]any); ok {
			if one_typed_here1_typed_root_value_b_lvl2_map, ok := one_typed_here1_typed_root_value_b_lvl1_map["typed_root"].(map[string]any); ok {
				if one_typed_here1_typed_root_value_b_val, ok := one_typed_here1_typed_root_value_b_lvl2_map["value_b"]; ok {
					assert.EqualValues(t, 45, one_typed_here1_typed_root_value_b_val)
				} else {
					t.Fatalf("Field 'value_b' not found in one_typed_here1_typed_root_value_b_lvl2_map (keys: %v)", maps.Keys(one_typed_here1_typed_root_value_b_lvl2_map))
				}
			} else {
				t.Fatalf("Field 'typed_root' not found or not a map while asserting One.TypedHere1.TypedRoot.ValueB")
			}
		} else {
			t.Fatalf("Field 'typed_here1' not found or not a map while asserting One.TypedHere1.TypedRoot.ValueB")
		}
	} else {
		t.Fatalf("Field 'one' not found or not a map while asserting One.TypedHere1.TypedRoot.ValueB")
	}

	// Assert One.TypedHere2.ValueCc
	if one_typed_here2_value_cc_lvl0_map, ok := customMap["one"].(map[string]any); ok {
		if one_typed_here2_value_cc_lvl1_map, ok := one_typed_here2_value_cc_lvl0_map["typed_here2"].(map[string]any); ok {
			if one_typed_here2_value_cc_val, ok := one_typed_here2_value_cc_lvl1_map["value_cc"]; ok {
				assert.EqualValues(t, 49, one_typed_here2_value_cc_val)
			} else {
				t.Fatalf("Field 'value_cc' not found in one_typed_here2_value_cc_lvl1_map (keys: %v)", maps.Keys(one_typed_here2_value_cc_lvl1_map))
			}
		} else {
			t.Fatalf("Field 'typed_here2' not found or not a map while asserting One.TypedHere2.ValueCc")
		}
	} else {
		t.Fatalf("Field 'one' not found or not a map while asserting One.TypedHere2.ValueCc")
	}

	// Assert Two.ValueB
	if two_value_b_lvl0_map, ok := customMap["two"].(map[string]any); ok {
		if two_value_b_val, ok := two_value_b_lvl0_map["value_b"]; ok {
			assert.EqualValues(t, -1, two_value_b_val)
		} else {
			t.Fatalf("Field 'value_b' not found in two_value_b_lvl0_map (keys: %v)", maps.Keys(two_value_b_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'two' not found or not a map while asserting Two.ValueB")
	}

}

func TestSerialize_NestedTypes2(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "nested_types2.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)

	serializer, err := kaitaistruct.NewKaitaiSerializer(schema, nil)
	require.NoError(t, err)

	// Read original binary
	binPath := filepath.Join("../../../test/src", "fixed_struct.bin")
	originalData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse original
	stream := kaitai.NewStream(bytes.NewReader(originalData))
	original := nested_types2_kaitai.NewNestedTypes2()
	err = original.Read(stream, original, original)
	require.NoError(t, err)

	// Serialize and verify round-trip
	inputMap := structToMapNestedTypes2(t, original)

	serialized, err := serializer.Serialize(context.Background(), inputMap)
	require.NoError(t, err)

	// Parse serialized data
	stream2 := kaitai.NewStream(bytes.NewReader(serialized))
	reparsed := nested_types2_kaitai.NewNestedTypes2()
	err = reparsed.Read(stream2, reparsed, reparsed)
	require.NoError(t, err)

	// Compare structures with Phase 2/3 enhanced comparison
	cmpOpts := []cmp.Option{
		cmpopts.IgnoreUnexported(
			kaitai.Stream{},
		),
		cmpopts.IgnoreFields(nested_types2_kaitai.NestedTypes2{}, "_io", "_parent", "_root"),
		cmpopts.EquateEmpty(),
	}
	if diff := cmp.Diff(original, reparsed, cmpOpts...); diff != "" {
		t.Errorf("Serialization mismatch (-original +reparsed):\n%s", diff)
	}
}

// structToMapNestedTypes2 converts KSC struct to map for serializer
func structToMapNestedTypes2(t *testing.T, data any) map[string]any {
	// Use reflection to handle KSC structs with method-based values
	return structToMapReflectiveNestedTypes2(t, data)
}

// structToMapReflectiveNestedTypes2 uses reflection to convert KSC structs including method calls
func structToMapReflectiveNestedTypes2(t *testing.T, data any) map[string]any {
	result := make(map[string]any)

	val := reflect.ValueOf(data)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	typ := val.Type()

	// Process fields
	for i := 0; i < val.NumField(); i++ {
		field := typ.Field(i)
		fieldVal := val.Field(i)

		// Skip internal KSC fields
		if strings.HasPrefix(field.Name, "_") {
			continue
		}

		fieldName := strings.ToLower(field.Name)

		if !fieldVal.IsValid() || fieldVal.IsZero() {
			continue
		}

		// Handle different field types
		switch fieldVal.Kind() {
		case reflect.Ptr:
			if !fieldVal.IsNil() {
				// For custom types, check for AsInt/AsStr methods
				subResult := make(map[string]any)

				// Try to call AsInt method
				if method := fieldVal.MethodByName("AsInt"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asint"] = results[0].Interface()
					}
				}

				// Try to call AsStr method
				if method := fieldVal.MethodByName("AsStr"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asstr"] = results[0].Interface()
					}
				}

				// Also include raw fields
				subMap := structToMapReflectiveNestedTypes2(t, fieldVal.Interface())
				for k, v := range subMap {
					if _, exists := subResult[k]; !exists {
						subResult[k] = v
					}
				}

				result[fieldName] = subResult
			}
		case reflect.Slice:
			if fieldVal.Len() > 0 {
				slice := make([]any, fieldVal.Len())
				for j := 0; j < fieldVal.Len(); j++ {
					slice[j] = fieldVal.Index(j).Interface()
				}
				result[fieldName] = slice
			}
		default:
			result[fieldName] = fieldVal.Interface()
		}
	}

	return result
}
