// Code generated by kaitai-test-gen-simple.go; DO NOT EDIT.
package formats_test

import (
	"bytes"
	"context"
	"log/slog"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/twinfer/kbin-plugin/pkg/kaitaistruct"
	opaque_external_type_02_parent_kaitai "github.com/twinfer/kbin-plugin/testdata/formats_kaitai_go_gen/opaque_external_type_02_parent"
)

func TestParse_OpaqueExternalType02Parent(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "opaque_external_type_02_parent.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)
	logger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug}))
	interpreter, err := kaitaistruct.NewKaitaiInterpreter(schema, logger)
	require.NoError(t, err)

	// Read binary file
	binPath := filepath.Join("../../../test/src", "term_strz.bin")
	binData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse with custom parser
	stream := kaitai.NewStream(bytes.NewReader(binData))
	parsed, err := interpreter.Parse(context.Background(), stream)
	require.NoError(t, err)

	// Convert to map for assertions
	customMap := kaitaistruct.ParsedDataToMap(parsed).(map[string]any)

	// Assertions from KSC test

	// Assert Parent.Child.S1
	if parent_child_s1_lvl0_map, ok := customMap["Parent"].(map[string]any); ok {
		if parent_child_s1_lvl1_map, ok := parent_child_s1_lvl0_map["Child"].(map[string]any); ok {
			if parent_child_s1_val, ok := parent_child_s1_lvl1_map["S1"]; ok {
				assert.EqualValues(t, "foo", parent_child_s1_val)
			} else {
				t.Fatalf("Field 'S1' not found in parent_child_s1_lvl1_map (keys: %v)", maps.Keys(parent_child_s1_lvl1_map))
			}
		} else {
			t.Fatalf("Field 'Child' not found or not a map while asserting Parent.Child.S1")
		}
	} else {
		t.Fatalf("Field 'Parent' not found or not a map while asserting Parent.Child.S1")
	}

	// Assert Parent.Child.S2
	if parent_child_s2_lvl0_map, ok := customMap["Parent"].(map[string]any); ok {
		if parent_child_s2_lvl1_map, ok := parent_child_s2_lvl0_map["Child"].(map[string]any); ok {
			if parent_child_s2_val, ok := parent_child_s2_lvl1_map["S2"]; ok {
				assert.EqualValues(t, "bar", parent_child_s2_val)
			} else {
				t.Fatalf("Field 'S2' not found in parent_child_s2_lvl1_map (keys: %v)", maps.Keys(parent_child_s2_lvl1_map))
			}
		} else {
			t.Fatalf("Field 'Child' not found or not a map while asserting Parent.Child.S2")
		}
	} else {
		t.Fatalf("Field 'Parent' not found or not a map while asserting Parent.Child.S2")
	}

	// Assert Parent.Child.S3.S3
	if parent_child_s3_s3_lvl0_map, ok := customMap["Parent"].(map[string]any); ok {
		if parent_child_s3_s3_lvl1_map, ok := parent_child_s3_s3_lvl0_map["Child"].(map[string]any); ok {
			if parent_child_s3_s3_lvl2_map, ok := parent_child_s3_s3_lvl1_map["S3"].(map[string]any); ok {
				if parent_child_s3_s3_val, ok := parent_child_s3_s3_lvl2_map["S3"]; ok {
					assert.EqualValues(t, "|baz@", parent_child_s3_s3_val)
				} else {
					t.Fatalf("Field 'S3' not found in parent_child_s3_s3_lvl2_map (keys: %v)", maps.Keys(parent_child_s3_s3_lvl2_map))
				}
			} else {
				t.Fatalf("Field 'S3' not found or not a map while asserting Parent.Child.S3.S3")
			}
		} else {
			t.Fatalf("Field 'Child' not found or not a map while asserting Parent.Child.S3.S3")
		}
	} else {
		t.Fatalf("Field 'Parent' not found or not a map while asserting Parent.Child.S3.S3")
	}

}

func TestSerialize_OpaqueExternalType02Parent(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "opaque_external_type_02_parent.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)

	serializer, err := kaitaistruct.NewKaitaiSerializer(schema, nil)
	require.NoError(t, err)

	// Read original binary
	binPath := filepath.Join("../../../test/src", "term_strz.bin")
	originalData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse original
	stream := kaitai.NewStream(bytes.NewReader(originalData))
	original := opaque_external_type_02_parent_kaitai.NewOpaqueExternalType02Parent()
	err = original.Read(stream, original, original)
	require.NoError(t, err)

	// Serialize and verify round-trip
	inputMap := structToMapOpaqueExternalType02Parent(t, original)

	serialized, err := serializer.Serialize(context.Background(), inputMap)
	require.NoError(t, err)

	// Parse serialized data
	stream2 := kaitai.NewStream(bytes.NewReader(serialized))
	reparsed := opaque_external_type_02_parent_kaitai.NewOpaqueExternalType02Parent()
	err = reparsed.Read(stream2, reparsed, reparsed)
	require.NoError(t, err)

	// Compare structures with Phase 2/3 enhanced comparison
	cmpOpts := []cmp.Option{
		cmpopts.IgnoreUnexported(
			kaitai.Stream{},
		),
		cmpopts.IgnoreFields(opaque_external_type_02_parent_kaitai.OpaqueExternalType02Parent{}, "_io", "_parent", "_root"),
		cmpopts.EquateEmpty(),
	}
	if diff := cmp.Diff(original, reparsed, cmpOpts...); diff != "" {
		t.Errorf("Serialization mismatch (-original +reparsed):\n%s", diff)
	}
}

// structToMapOpaqueExternalType02Parent converts KSC struct to map for serializer
func structToMapOpaqueExternalType02Parent(t *testing.T, data any) map[string]any {
	// Use reflection to handle KSC structs with method-based values
	return structToMapReflectiveOpaqueExternalType02Parent(t, data)
}

// structToMapReflectiveOpaqueExternalType02Parent uses reflection to convert KSC structs including method calls
func structToMapReflectiveOpaqueExternalType02Parent(t *testing.T, data any) map[string]any {
	result := make(map[string]any)

	val := reflect.ValueOf(data)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	typ := val.Type()

	// Process fields
	for i := 0; i < val.NumField(); i++ {
		field := typ.Field(i)
		fieldVal := val.Field(i)

		// Skip internal KSC fields
		if strings.HasPrefix(field.Name, "_") {
			continue
		}

		fieldName := strings.ToLower(field.Name)

		if !fieldVal.IsValid() || fieldVal.IsZero() {
			continue
		}

		// Handle different field types
		switch fieldVal.Kind() {
		case reflect.Ptr:
			if !fieldVal.IsNil() {
				// For custom types, check for AsInt/AsStr methods
				subResult := make(map[string]any)

				// Try to call AsInt method
				if method := fieldVal.MethodByName("AsInt"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asint"] = results[0].Interface()
					}
				}

				// Try to call AsStr method
				if method := fieldVal.MethodByName("AsStr"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asstr"] = results[0].Interface()
					}
				}

				// Also include raw fields
				subMap := structToMapReflectiveOpaqueExternalType02Parent(t, fieldVal.Interface())
				for k, v := range subMap {
					if _, exists := subResult[k]; !exists {
						subResult[k] = v
					}
				}

				result[fieldName] = subResult
			}
		case reflect.Slice:
			if fieldVal.Len() > 0 {
				slice := make([]any, fieldVal.Len())
				for j := 0; j < fieldVal.Len(); j++ {
					slice[j] = fieldVal.Index(j).Interface()
				}
				result[fieldName] = slice
			}
		default:
			result[fieldName] = fieldVal.Interface()
		}
	}

	return result
}
