// Code generated by kaitai-test-gen-simple.go; DO NOT EDIT.
package formats_test

import (
	"bytes"
	"context"
	"log/slog"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/twinfer/kbin-plugin/pkg/kaitaistruct"
	term_strz_utf16_v4_kaitai "github.com/twinfer/kbin-plugin/testdata/formats_kaitai_go_gen/term_strz_utf16_v4"
)

func TestParse_TermStrzUtf16V4(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "term_strz_utf16_v4.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)
	logger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug}))
	interpreter, err := kaitaistruct.NewKaitaiInterpreter(schema, logger)
	require.NoError(t, err)

	// Read binary file
	binPath := filepath.Join("../../../test/src", "term_strz_utf16.bin")
	binData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse with custom parser
	stream := kaitai.NewStream(bytes.NewReader(binData))
	parsed, err := interpreter.Parse(context.Background(), stream)
	require.NoError(t, err)

	// Convert to map for assertions
	customMap := kaitaistruct.ParsedDataToMap(parsed).(map[string]any)

	// Assertions from KSC test

	// Assert S1.Value
	if s1_value_lvl0_map, ok := customMap["S1"].(map[string]any); ok {
		if s1_value_val, ok := s1_value_lvl0_map["Value"]; ok {
			assert.EqualValues(t, "a\u0200b", s1_value_val)
		} else {
			t.Fatalf("Field 'Value' not found in s1_value_lvl0_map (keys: %v)", maps.Keys(s1_value_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'S1' not found or not a map while asserting S1.Value")
	}

	// Assert S2.Value
	if s2_value_lvl0_map, ok := customMap["S2"].(map[string]any); ok {
		if s2_value_val, ok := s2_value_lvl0_map["Value"]; ok {
			assert.EqualValues(t, "c\u0200d", s2_value_val)
		} else {
			t.Fatalf("Field 'Value' not found in s2_value_lvl0_map (keys: %v)", maps.Keys(s2_value_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'S2' not found or not a map while asserting S2.Value")
	}

	// Assert S3.Value
	if s3_value_lvl0_map, ok := customMap["S3"].(map[string]any); ok {
		if s3_value_val, ok := s3_value_lvl0_map["Value"]; ok {
			assert.EqualValues(t, "e\u0200f", s3_value_val)
		} else {
			t.Fatalf("Field 'Value' not found in s3_value_lvl0_map (keys: %v)", maps.Keys(s3_value_lvl0_map))
		}
	} else {
		t.Fatalf("Field 'S3' not found or not a map while asserting S3.Value")
	}

}

func TestSerialize_TermStrzUtf16V4(t *testing.T) {
	// Load schema
	ksyPath := filepath.Join("../../../test/formats", "term_strz_utf16_v4.ksy")
	yamlData, err := os.ReadFile(ksyPath)
	require.NoError(t, err)

	schema, err := kaitaistruct.NewKaitaiSchemaFromYAML(yamlData)
	require.NoError(t, err)

	serializer, err := kaitaistruct.NewKaitaiSerializer(schema, nil)
	require.NoError(t, err)

	// Read original binary
	binPath := filepath.Join("../../../test/src", "term_strz_utf16.bin")
	originalData, err := os.ReadFile(binPath)
	require.NoError(t, err)

	// Parse original
	stream := kaitai.NewStream(bytes.NewReader(originalData))
	original := term_strz_utf16_v4_kaitai.NewTermStrzUtf16V4()
	err = original.Read(stream, original, original)
	require.NoError(t, err)

	// Serialize and verify round-trip
	inputMap := structToMapTermStrzUtf16V4(t, original)

	serialized, err := serializer.Serialize(context.Background(), inputMap)
	require.NoError(t, err)

	// Parse serialized data
	stream2 := kaitai.NewStream(bytes.NewReader(serialized))
	reparsed := term_strz_utf16_v4_kaitai.NewTermStrzUtf16V4()
	err = reparsed.Read(stream2, reparsed, reparsed)
	require.NoError(t, err)

	// Compare structures with Phase 2/3 enhanced comparison
	cmpOpts := []cmp.Option{
		cmpopts.IgnoreUnexported(
			kaitai.Stream{},
		),
		cmpopts.IgnoreFields(term_strz_utf16_v4_kaitai.TermStrzUtf16V4{}, "_io", "_parent", "_root"),
		cmpopts.EquateEmpty(),
	}
	if diff := cmp.Diff(original, reparsed, cmpOpts...); diff != "" {
		t.Errorf("Serialization mismatch (-original +reparsed):\n%s", diff)
	}
}

// structToMapTermStrzUtf16V4 converts KSC struct to map for serializer
func structToMapTermStrzUtf16V4(t *testing.T, data any) map[string]any {
	// Use reflection to handle KSC structs with method-based values
	return structToMapReflectiveTermStrzUtf16V4(t, data)
}

// structToMapReflectiveTermStrzUtf16V4 uses reflection to convert KSC structs including method calls
func structToMapReflectiveTermStrzUtf16V4(t *testing.T, data any) map[string]any {
	result := make(map[string]any)

	val := reflect.ValueOf(data)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	typ := val.Type()

	// Process fields
	for i := 0; i < val.NumField(); i++ {
		field := typ.Field(i)
		fieldVal := val.Field(i)

		// Skip internal KSC fields
		if strings.HasPrefix(field.Name, "_") {
			continue
		}

		fieldName := strings.ToLower(field.Name)

		if !fieldVal.IsValid() || fieldVal.IsZero() {
			continue
		}

		// Handle different field types
		switch fieldVal.Kind() {
		case reflect.Ptr:
			if !fieldVal.IsNil() {
				// For custom types, check for AsInt/AsStr methods
				subResult := make(map[string]any)

				// Try to call AsInt method
				if method := fieldVal.MethodByName("AsInt"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asint"] = results[0].Interface()
					}
				}

				// Try to call AsStr method
				if method := fieldVal.MethodByName("AsStr"); method.IsValid() {
					if results := method.Call(nil); len(results) == 2 && results[1].IsNil() {
						subResult["asstr"] = results[0].Interface()
					}
				}

				// Also include raw fields
				subMap := structToMapReflectiveTermStrzUtf16V4(t, fieldVal.Interface())
				for k, v := range subMap {
					if _, exists := subResult[k]; !exists {
						subResult[k] = v
					}
				}

				result[fieldName] = subResult
			}
		case reflect.Slice:
			if fieldVal.Len() > 0 {
				slice := make([]any, fieldVal.Len())
				for j := 0; j < fieldVal.Len(); j++ {
					slice[j] = fieldVal.Index(j).Interface()
				}
				result[fieldName] = slice
			}
		default:
			result[fieldName] = fieldVal.Interface()
		}
	}

	return result
}
